In [28]:
import pandas as pd 
import numpy as np

In [29]:
from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)

In [30]:
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
avg_hh_dd = pd.read_excel('avg_hh_demand_reformatted.xlsx')
demand_supply = pd.read_excel('Demand_Supply.xlsx')

In [31]:
# sum columns for each table
sum_max_hh_dd = max_hh_dd.sum()
sum_min_hh_dd = min_hh_dd.sum()
sum_avg_hh_dd = avg_hh_dd.sum()

In [32]:
# Power supplied
ss_power = demand_supply['SS_Power']

In [33]:
hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

## Total Loss Max

In [34]:
sum_max_hh_dd.values

array([ 2.32000284,  2.1854947 ,  1.97468306,  2.45862135,  3.32336774,
        4.07009235,  7.17424938,  8.35041245, 16.90151425, 14.90945729,
       10.59417502,  9.12553079,  6.84790155, 11.04675339, 10.87769295,
       12.42037993,  9.35330303, 11.52157111, 12.84026514, 10.23134478,
        6.08890037,  4.5802809 ,  2.84020214,  2.84636513])

In [35]:
ss_power.values

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [36]:
total_loss_max = sum_max_hh_dd.values - ss_power.values

In [37]:
total_loss_max

array([-2.81199716, -2.2265053 , -1.84131694, -0.96937865, -0.01663226,
        0.65809235,  3.26624938,  4.55841245, 10.43351425,  9.07745729,
        2.76217502,  1.23353079, -0.55209845,  2.17875339,  2.98969295,
        4.82837993,  1.08530303,  2.13757111,  4.82426514,  0.46734478,
       -6.17909963, -6.4037191 , -5.69179786, -3.34163487])

In [43]:
new_total_loss_max = np.maximum(total_loss_max, np.zeros_like(total_loss_max))

In [44]:
new_total_loss_max

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.65809235,  3.26624938,  4.55841245, 10.43351425,  9.07745729,
        2.76217502,  1.23353079,  0.        ,  2.17875339,  2.98969295,
        4.82837993,  1.08530303,  2.13757111,  4.82426514,  0.46734478,
        0.        ,  0.        ,  0.        ,  0.        ])

In [45]:
power_loss_max = pd.DataFrame({'Hour': hours, 'Total_Loss_Max': new_total_loss_max})

In [46]:
power_loss_max

Hour  Total_Loss_Max
0      1        0.000000
1      2        0.000000
2      3        0.000000
3      4        0.000000
4      5        0.000000
5      6        0.658092
6      7        3.266249
7      8        4.558412
8      9       10.433514
9     10        9.077457
10    11        2.762175
11    12        1.233531
12    13        0.000000
13    14        2.178753
14    15        2.989693
15    16        4.828380
16    17        1.085303
17    18        2.137571
18    19        4.824265
19    20        0.467345
20    21        0.000000
21    22        0.000000
22    23        0.000000
23    24        0.000000

In [47]:
power_loss_max.to_excel('Total_Loss_Max.xlsx', index=False)

## Total Loss Min

In [48]:
sum_min_hh_dd.values

array([ 1.73629914,  1.67500471,  1.70160429,  2.11973421,  2.31624109,
        3.0513202 ,  2.51534798,  5.83521829,  7.48697929,  8.23049991,
        5.42470836,  7.42006604,  5.95932768,  5.27180218,  7.85913904,
        8.71311713,  7.668663  , 10.12452073,  8.64237932,  4.73603721,
        4.61412439,  3.25995703,  2.65578999,  2.09959916])

In [49]:
ss_power.values

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [50]:
total_loss_min = sum_min_hh_dd.values - ss_power.values

In [51]:
total_loss_min

array([-3.39570086, -2.73699529, -2.11439571, -1.30826579, -1.02375891,
       -0.3606798 , -1.39265202,  2.04321829,  1.01897929,  2.39849991,
       -2.40729164, -0.47193396, -1.44067232, -3.59619782, -0.02886096,
        1.12111713, -0.599337  ,  0.74052073,  0.62637932, -5.02796279,
       -7.65387561, -7.72404297, -5.87621001, -4.08840084])

In [52]:
new_total_loss_min = np.maximum(total_loss_min, np.zeros_like(total_loss_min))

In [53]:
new_total_loss_min

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 2.04321829, 1.01897929, 2.39849991,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.12111713, 0.        , 0.74052073, 0.62637932, 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [54]:
power_loss_min = pd.DataFrame({'Hour': hours, 'Total_Loss_Min': new_total_loss_min})

In [55]:
power_loss_min

Hour  Total_Loss_Min
0      1        0.000000
1      2        0.000000
2      3        0.000000
3      4        0.000000
4      5        0.000000
5      6        0.000000
6      7        0.000000
7      8        2.043218
8      9        1.018979
9     10        2.398500
10    11        0.000000
11    12        0.000000
12    13        0.000000
13    14        0.000000
14    15        0.000000
15    16        1.121117
16    17        0.000000
17    18        0.740521
18    19        0.626379
19    20        0.000000
20    21        0.000000
21    22        0.000000
22    23        0.000000
23    24        0.000000

In [56]:
power_loss_min.to_excel('Total_Loss_Min.xlsx', index=False)

## Total Loss Avg

In [57]:
sum_avg_hh_dd.values


array([ 2.09538549,  1.93703121,  1.82532894,  2.25633735,  2.73834278,
        3.586944  ,  4.47808035,  7.02269024, 12.15675289, 11.12963442,
        7.63444497,  8.3499341 ,  6.42770185,  8.13867747,  9.39972857,
       10.51375305,  8.56062885, 10.91466267, 10.58634462,  7.72342311,
        5.43210867,  4.00038852,  2.7551632 ,  2.44196724])

In [58]:
ss_power.values

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [59]:
total_loss_avg = sum_avg_hh_dd.values - ss_power.values

In [60]:
total_loss_avg

array([-3.03661451, -2.47496879, -1.99067106, -1.17166265, -0.60165722,
        0.174944  ,  0.57008035,  3.23069024,  5.68875289,  5.29763442,
       -0.19755503,  0.4579341 , -0.97229815, -0.72932253,  1.51172857,
        2.92175305,  0.29262885,  1.53066267,  2.57034462, -2.04057689,
       -6.83589133, -6.98361148, -5.7768368 , -3.74603276])

In [61]:
new_total_loss_avg = np.maximum(total_loss_avg, np.zeros_like(total_loss_avg))

In [62]:
new_total_loss_avg

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.174944  , 0.57008035, 3.23069024, 5.68875289, 5.29763442,
       0.        , 0.4579341 , 0.        , 0.        , 1.51172857,
       2.92175305, 0.29262885, 1.53066267, 2.57034462, 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [63]:
power_loss_avg = pd.DataFrame({'Hour': hours, 'Total_Loss_Avg': new_total_loss_avg})

In [64]:
power_loss_avg

Hour  Total_Loss_Avg
0      1        0.000000
1      2        0.000000
2      3        0.000000
3      4        0.000000
4      5        0.000000
5      6        0.174944
6      7        0.570080
7      8        3.230690
8      9        5.688753
9     10        5.297634
10    11        0.000000
11    12        0.457934
12    13        0.000000
13    14        0.000000
14    15        1.511729
15    16        2.921753
16    17        0.292629
17    18        1.530663
18    19        2.570345
19    20        0.000000
20    21        0.000000
21    22        0.000000
22    23        0.000000
23    24        0.000000

In [65]:
power_loss_avg.to_excel('Total_Loss_Avg.xlsx', index=False)

## Power Loss Per household

In [69]:
total_loss_min_per_household = new_total_loss_min/156
total_loss_max_per_household = new_total_loss_max/156
total_loss_avg_per_household = new_total_loss_avg/156

In [75]:
total_loss_min_per_household

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01309755, 0.00653192, 0.015375  ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00718665, 0.        , 0.00474693, 0.00401525, 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [76]:
total_loss_avg_per_household

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00112144, 0.00365436, 0.02070955, 0.03646636, 0.0339592 ,
       0.        , 0.00293547, 0.        , 0.        , 0.00969057,
       0.01872919, 0.00187583, 0.00981194, 0.01647657, 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [77]:
total_loss_max_per_household

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00421854, 0.0209375 , 0.02922059, 0.0668815 , 0.05818883,
       0.01770625, 0.00790725, 0.        , 0.01396637, 0.0191647 ,
       0.03095115, 0.00695707, 0.01370238, 0.03092478, 0.0029958 ,
       0.        , 0.        , 0.        , 0.        ])

## Allocated Power

In [78]:
min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.04088393, 0.04866755, 0.05500866,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.05163881, 0.04707744, 0.06572936, 0.0547874 , 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.03460951, 0.04255457, 0.05803668,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.05508243, 0.0449173 , 0.06526549, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.0413863 , 0.04282187, 0.04856956,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.05396384, 0.04680111, 0.06601068, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [73]:
allocated_power_min = min_hh_dd.values - total_loss_min_per_household

In [74]:
allocated_power_min

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.02778638, 0.04213564, 0.03963366,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.04445217, 0.04707744, 0.06098243, 0.05077215, 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.02151195, 0.03602265, 0.04266168,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.04789578, 0.0449173 , 0.06051857, 0.04545789, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.02828875, 0.03628996, 0.03319456,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.0467772 , 0.04680111, 0.06126376, 0.04688198, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [84]:
allocated_power_cel_min = np.maximum(allocated_power_min,  np.zeros_like(allocated_power_min))

In [85]:
allocated_power_cel_min

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.02778638, 0.04213564, 0.03963366,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.04445217, 0.04707744, 0.06098243, 0.05077215, 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.02151195, 0.03602265, 0.04266168,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.04789578, 0.0449173 , 0.06051857, 0.04545789, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.02828875, 0.03628996, 0.03319456,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.0467772 , 0.04680111, 0.06126376, 0.04688198, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [87]:
columns = ['allocated_power_cel_min_hour_1',
           'allocated_power_cel_min_hour_2',
           'allocated_power_cel_min_hour_3',
           'allocated_power_cel_min_hour_4',
           'allocated_power_cel_min_hour_5',
           'allocated_power_cel_min_hour_6',
           'allocated_power_cel_min_hour_7',
           'allocated_power_cel_min_hour_8',
           'allocated_power_cel_min_hour_9',
           'allocated_power_cel_min_hour_10',
           'allocated_power_cel_min_hour_11',
           'allocated_power_cel_min_hour_12',
           'allocated_power_cel_min_hour_13',
           'allocated_power_cel_min_hour_14',
           'allocated_power_cel_min_hour_15',
           'allocated_power_cel_min_hour_16',
           'allocated_power_cel_min_hour_17',
           'allocated_power_cel_min_hour_18',
           'allocated_power_cel_min_hour_19',
           'allocated_power_cel_min_hour_20',
           'allocated_power_cel_min_hour_21',
           'allocated_power_cel_min_hour_22',
           'allocated_power_cel_min_hour_23',
           'allocated_power_cel_min_hour_24']

In [88]:
allocated_power_cel_min = pd.DataFrame(allocated_power_cel_min, columns=columns)

In [89]:
allocated_power_cel_min

allocated_power_cel_min_hour_1  allocated_power_cel_min_hour_2  \
0                          0.010768                        0.012001   
1                          0.010985                        0.011571   
2                          0.011227                        0.010011   
3                          0.009785                        0.011650   
4                          0.011163                        0.010641   
..                              ...                             ...   
151                        0.010435                        0.010214   
152                        0.011361                        0.012128   
153                        0.011701                        0.009820   
154                        0.012332                        0.011266   
155                        0.010685                        0.011699   

     allocated_power_cel_min_hour_3  allocated_power_cel_min_hour_4  \
0                          0.011594                        0.013803   
1                          0.010191                        0.013530   
2                          0.012221                        0.014374   
3                          0.011528                        0.014225   
4                          0.009732                        0.012215   
..                              ...                             ...   
151                        0.009667                        0.014683   
152                        0.011693                        0.013153   
153                        0.011268                        0.012775   
154                        0.012125                        0.012725   
155                        0.012131                        0.012467   

     allocated_power_cel_min_hour_5  allocated_power_cel_min_hour_6  \
0                          0.013546                        0.017943   
1                          0.015093                        0.017429   
2                          0.016323                        0.021411   
3                          0.015727                        0.017559   
4                          0.013105                        0.020198   
..                              ...                             ...   
151                        0.015802                        0.020156   
152                        0.015926                        0.018012   
153                        0.013608                        0.018994   
154                        0.015160                        0.020396   
155                        0.014313                        0.021570   

     allocated_power_cel_min_hour_7  allocated_power_cel_min_hour_8  \
0                          0.014342                        0.027786   
1                          0.016458                        0.021512   
2                          0.016421                        0.028289   
3                          0.015499                        0.021019   
4                          0.015329                        0.024561   
..                              ...                             ...   
151                        0.017007                        0.021345   
152                        0.014236                        0.021818   
153                        0.017205                        0.023510   
154                        0.015341                        0.027623   
155                        0.014357                        0.020807   

     allocated_power_cel_min_hour_9  allocated_power_cel_min_hour_10  ...  \
0                          0.042136                         0.039634  ...   
1                          0.036023                         0.042662  ...   
2                          0.036290                         0.033195  ...   
3                          0.045123                         0.038568  ...   
4                          0.045630                         0.033865  ...   
..                              ...                              ...  ...   
151                        0.040507                   

In [90]:
allocated_power_cel_min.to_excel('allocated_power_cel_min.xlsx', index=False)

## allocated cel max

In [91]:
allocated_power_max = max_hh_dd.values - total_loss_max_per_household

In [92]:
allocated_power_cel_max = np.maximum(allocated_power_max,  np.zeros_like(allocated_power_max))

In [93]:
columns = ['allocated_power_cel_max_hour_1',
           'allocated_power_cel_max_hour_2',
           'allocated_power_cel_max_hour_3',
           'allocated_power_cel_max_hour_4',
           'allocated_power_cel_max_hour_5',
           'allocated_power_cel_max_hour_6',
           'allocated_power_cel_max_hour_7',
           'allocated_power_cel_max_hour_8',
           'allocated_power_cel_max_hour_9',
           'allocated_power_cel_max_hour_10',
           'allocated_power_cel_max_hour_11',
           'allocated_power_cel_max_hour_12',
           'allocated_power_cel_max_hour_13',
           'allocated_power_cel_max_hour_14',
           'allocated_power_cel_max_hour_15',
           'allocated_power_cel_max_hour_16',
           'allocated_power_cel_max_hour_17',
           'allocated_power_cel_max_hour_18',
           'allocated_power_cel_max_hour_19',
           'allocated_power_cel_max_hour_20',
           'allocated_power_cel_max_hour_21',
           'allocated_power_cel_max_hour_22',
           'allocated_power_cel_max_hour_23',
           'allocated_power_cel_max_hour_24']

In [94]:
allocated_power_cel_max = pd.DataFrame(allocated_power_cel_max, columns=columns)

In [95]:
allocated_power_cel_max

allocated_power_cel_max_hour_1  allocated_power_cel_max_hour_2  \
0                          0.014388                        0.015659   
1                          0.014678                        0.015097   
2                          0.015001                        0.013061   
3                          0.013074                        0.015200   
4                          0.014916                        0.013884   
..                              ...                             ...   
151                        0.013944                        0.013327   
152                        0.015180                        0.015824   
153                        0.015635                        0.012813   
154                        0.016478                        0.014699   
155                        0.014277                        0.015265   

     allocated_power_cel_max_hour_3  allocated_power_cel_max_hour_4  \
0                          0.013455                        0.016010   
1                          0.011827                        0.015693   
2                          0.014182                        0.016672   
3                          0.013378                        0.016499   
4                          0.011294                        0.014167   
..                              ...                             ...   
151                        0.011218                        0.017031   
152                        0.013570                        0.015256   
153                        0.013077                        0.014817   
154                        0.014071                        0.014759   
155                        0.014078                        0.014460   

     allocated_power_cel_max_hour_5  allocated_power_cel_max_hour_6  \
0                          0.019436                        0.019716   
1                          0.021655                        0.019030   
2                          0.023420                        0.024342   
3                          0.022565                        0.019203   
4                          0.018803                        0.022724   
..                              ...                             ...   
151                        0.022673                        0.022667   
152                        0.022851                        0.019808   
153                        0.019525                        0.021117   
154                        0.021752                        0.022987   
155                        0.020537                        0.024553   

     allocated_power_cel_max_hour_7  allocated_power_cel_max_hour_8  \
0                          0.019969                        0.029286   
1                          0.026004                        0.020307   
2                          0.025898                        0.030005   
3                          0.023268                        0.019601   
4                          0.022784                        0.024670   
..                              ...                             ...   
151                        0.027571                        0.020068   
152                        0.019666                        0.020745   
153                        0.028133                        0.023167   
154                        0.022819                        0.029053   
155                        0.020010                        0.019298   

     allocated_power_cel_max_hour_9  allocated_power_cel_max_hour_10  ...  \
0                          0.042983                         0.041459  ...   
1                          0.029183                         0.046944  ...   
2                          0.029787                         0.029794  ...   
3                          0.049728                         0.039528  ...   
4                          0.050872                         0.031009  ...   
..                              ...                              ...  ...   
151                        0.039307                   

In [96]:
allocated_power_cel_max.to_excel('allocated_power_cel_max.xlsx', index=False)

## allocated power cel avg

In [97]:
allocated_power_avg = avg_hh_dd.values - total_loss_avg_per_household

In [98]:
allocated_power_cel_avg = np.maximum(allocated_power_avg,  np.zeros_like(allocated_power_avg))

In [99]:
columns = ['allocated_power_cel_avg_hour_1',
           'allocated_power_cel_avg_hour_2',
           'allocated_power_cel_avg_hour_3',
           'allocated_power_cel_avg_hour_4',
           'allocated_power_cel_avg_hour_5',
           'allocated_power_cel_avg_hour_6',
           'allocated_power_cel_avg_hour_7',
           'allocated_power_cel_avg_hour_8',
           'allocated_power_cel_avg_hour_9',
           'allocated_power_cel_avg_hour_10',
           'allocated_power_cel_avg_hour_11',
           'allocated_power_cel_avg_hour_12',
           'allocated_power_cel_avg_hour_13',
           'allocated_power_cel_avg_hour_14',
           'allocated_power_cel_avg_hour_15',
           'allocated_power_cel_avg_hour_16',
           'allocated_power_cel_avg_hour_17',
           'allocated_power_cel_avg_hour_18',
           'allocated_power_cel_avg_hour_19',
           'allocated_power_cel_avg_hour_20',
           'allocated_power_cel_avg_hour_21',
           'allocated_power_cel_avg_hour_22',
           'allocated_power_cel_avg_hour_23',
           'allocated_power_cel_avg_hour_24']

In [100]:
allocated_power_cel_avg = pd.DataFrame(allocated_power_cel_avg, columns=columns)

In [101]:
allocated_power_cel_avg

allocated_power_cel_avg_hour_1  allocated_power_cel_avg_hour_2  \
0                          0.012995                        0.013878   
1                          0.013257                        0.013381   
2                          0.013549                        0.011576   
3                          0.011809                        0.013472   
4                          0.013472                        0.012306   
..                              ...                             ...   
151                        0.012594                        0.011812   
152                        0.013710                        0.014025   
153                        0.014121                        0.011356   
154                        0.014883                        0.013028   
155                        0.012895                        0.013529   

     allocated_power_cel_avg_hour_3  allocated_power_cel_avg_hour_4  \
0                          0.012438                        0.014692   
1                          0.010932                        0.014402   
2                          0.013109                        0.015300   
3                          0.012366                        0.015141   
4                          0.010440                        0.013002   
..                              ...                             ...   
151                        0.010370                        0.015629   
152                        0.012543                        0.014001   
153                        0.012088                        0.013598   
154                        0.013006                        0.013545   
155                        0.013013                        0.013270   

     allocated_power_cel_avg_hour_5  allocated_power_cel_avg_hour_6  \
0                          0.016015                        0.019972   
1                          0.017843                        0.019367   
2                          0.019297                        0.024048   
3                          0.018592                        0.019519   
4                          0.015493                        0.022622   
..                              ...                             ...   
151                        0.018682                        0.022572   
152                        0.018828                        0.020053   
153                        0.016088                        0.021206   
154                        0.017923                        0.022855   
155                        0.016922                        0.024235   

     allocated_power_cel_avg_hour_7  allocated_power_cel_avg_hour_8  \
0                          0.021879                        0.028494   
1                          0.025646                        0.020943   
2                          0.025580                        0.029099   
3                          0.023938                        0.020350   
4                          0.023636                        0.024613   
..                              ...                             ...   
151                        0.026624                        0.020742   
152                        0.021690                        0.021311   
153                        0.026975                        0.023348   
154                        0.023658                        0.028298   
155                        0.021905                        0.020095   

     allocated_power_cel_avg_hour_9  allocated_power_cel_avg_hour_10  ...  \
0                          0.042556                         0.040426  ...   
1                          0.032630                         0.044520  ...   
2                          0.033064                         0.031719  ...   
3                          0.047407                         0.038984  ...   
4                          0.048230                         0.032625  ...   
..                              ...                              ...  ...   
151                        0.039912                   

In [102]:
allocated_power_cel_avg.to_excel('allocated_power_cel_avg.xlsx', index=False)