In [9]:
import pandas as pd
import numpy as np

from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)

In [10]:
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
power_allocated_demand_from_max_hh_dd = pd.read_excel('power_allocated_demand_from_max_hh_dd.xlsx')
power_allocated_demand_from_min_hh_dd = pd.read_excel('power_allocated_demand_from_min_hh_dd.xlsx')

## Min unmet demand

In [11]:
min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.04088393, 0.04866755, 0.05500866,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.05163881, 0.04707744, 0.06572936, 0.0547874 , 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.03460951, 0.04255457, 0.05803668,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.05508243, 0.0449173 , 0.06526549, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.0413863 , 0.04282187, 0.04856956,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.05396384, 0.04680111, 0.06601068, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [12]:
power_allocated_demand_from_min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.02656831, 0.04204389, 0.03897825,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.04499445, 0.04707744, 0.06092182, 0.05081654, 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.02249089, 0.03676288, 0.04112386,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.04799497, 0.0449173 , 0.06049189, 0.04588744, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.02689477, 0.03699381, 0.03441561,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.04702031, 0.04680111, 0.06118258, 0.04720832, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [13]:
min_unmet_demand = min_hh_dd.values - power_allocated_demand_from_min_hh_dd.values

In [14]:
min_unmet_demand

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01431563, 0.00662366, 0.01603041,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00664437, 0.        , 0.00480753, 0.00397086, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01211862, 0.00579168, 0.01691282,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00708746, 0.        , 0.0047736 , 0.0035857 , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01449153, 0.00582807, 0.01415395,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00694353, 0.        , 0.00482811, 0.00368891, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [15]:
column_names = ['min_unmet_demand_hour_1',
                'min_unmet_demand_hour_2',
                'min_unmet_demand_hour_3',
                'min_unmet_demand_hour_4',
                'min_unmet_demand_hour_5',
                'min_unmet_demand_hour_6',
                'min_unmet_demand_hour_7',
                'min_unmet_demand_hour_8',
                'min_unmet_demand_hour_9',
                'min_unmet_demand_hour_10',
                'min_unmet_demand_hour_11',
                'min_unmet_demand_hour_12',
                'min_unmet_demand_hour_13',
                'min_unmet_demand_hour_14',
                'min_unmet_demand_hour_15',
                'min_unmet_demand_hour_16',
                'min_unmet_demand_hour_17',
                'min_unmet_demand_hour_18',
                'min_unmet_demand_hour_19',
                'min_unmet_demand_hour_20',
                'min_unmet_demand_hour_21',
                'min_unmet_demand_hour_22',
                'min_unmet_demand_hour_23',
                'min_unmet_demand_hour_24',]

In [16]:
min_unmet_demand = pd.DataFrame(min_unmet_demand, columns=column_names)

In [17]:
min_unmet_demand

min_unmet_demand_hour_1  min_unmet_demand_hour_2  \
0                        0.0                      0.0   
1                        0.0                      0.0   
2                        0.0                      0.0   
3                        0.0                      0.0   
4                        0.0                      0.0   
..                       ...                      ...   
151                      0.0                      0.0   
152                      0.0                      0.0   
153                      0.0                      0.0   
154                      0.0                      0.0   
155                      0.0                      0.0   

     min_unmet_demand_hour_3  min_unmet_demand_hour_4  \
0                        0.0                      0.0   
1                        0.0                      0.0   
2                        0.0                      0.0   
3                        0.0                      0.0   
4                        0.0                      0.0   
..                       ...                      ...   
151                      0.0                      0.0   
152                      0.0                      0.0   
153                      0.0                      0.0   
154                      0.0                      0.0   
155                      0.0                      0.0   

     min_unmet_demand_hour_5  min_unmet_demand_hour_6  \
0                        0.0                      0.0   
1                        0.0                      0.0   
2                        0.0                      0.0   
3                        0.0                      0.0   
4                        0.0                      0.0   
..                       ...                      ...   
151                      0.0                      0.0   
152                      0.0                      0.0   
153                      0.0                      0.0   
154                      0.0                      0.0   
155                      0.0                      0.0   

     min_unmet_demand_hour_7  min_unmet_demand_hour_8  \
0                        0.0                 0.014316   
1                        0.0                 0.012119   
2                        0.0                 0.014492   
3                        0.0                 0.011946   
4                        0.0                 0.013186   
..                       ...                      ...   
151                      0.0                 0.012060   
152                      0.0                 0.012226   
153                      0.0                 0.012818   
154                      0.0                 0.014259   
155                      0.0                 0.011872   

     min_unmet_demand_hour_9  min_unmet_demand_hour_10  ...  \
0                   0.006624                  0.016030  ...   
1                   0.005792                  0.016913  ...   
2                   0.005828                  0.014154  ...   
3                   0.007030                  0.015720  ...   
4                   0.007099                  0.014349  ...   
..                       ...                       ...  ...   
151                 0.006402                  0.014723  ...   
152                 0.006219                  0.015307  ...   
153                 0.006856                  0.013896  ...   
154                 0.007161                  0.016678  ...   
155                 0.005943                  0.015617  ...   

     min_unmet_demand_hour_15  min_unmet_demand_hour_16  \
0                         0.0                  0.006644   
1                         0.0                  0.007087   
2                         0.0                  0.006944   
3                         0.0                  0.007428   
4                         0.0                  0.006606   
..                        ...                       ...   
151                       0.0                  0.006686   
152                       0.0       

In [18]:
min_unmet_demand.to_excel('min_unmet_demand.xlsx', index=False)

## Max unmet demand

In [19]:
max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02393417, 0.04090667, 0.05850642, 0.10986478, 0.09964756,
        0.06038371, 0.0646918 , 0.04739652, 0.06559203, 0.06516239,
        0.07361013, 0.05741933, 0.07479914, 0.08139943, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.0232483 , 0.04694107, 0.04952748, 0.09606499, 0.10513278,
        0.07586014, 0.0624383 , 0.04183603, 0.06365307, 0.07366913,
        0.07851894, 0.05478466, 0.07427127, 0.07350386, 0.07211744,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.0285601 , 0.04683515, 0.05922532, 0.09666843, 0.08798321,
        0.06078727, 0.05569831, 0.04272161, 0.06658986, 0.07611587,
        0.07692442, 0.0570823 , 0.07511929, 0.07561968, 0.07042918,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [20]:
power_allocated_demand_from_max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02006426, 0.02228293, 0.02656831, 0.04204389, 0.03897825,
        0.04464012, 0.05594718, 0.04739652, 0.0526553 , 0.04725275,
        0.04499445, 0.05075673, 0.06092182, 0.05081654, 0.05952713,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.01948929, 0.02557002, 0.02249089, 0.03676288, 0.04112386,
        0.05608145, 0.05399829, 0.04183603, 0.05109876, 0.05342145,
        0.04799497, 0.04842777, 0.06049189, 0.04588744, 0.06882328,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.02394222, 0.02551232, 0.02689477, 0.03699381, 0.03441561,
        0.04493846, 0.04816937, 0.04272161, 0.05345633, 0.05519571,
        0.04702031, 0.0504588 , 0.06118258, 0.04720832, 0.06721213,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [21]:
max_unmet_demand = max_hh_dd.values - power_allocated_demand_from_max_hh_dd.values

In [22]:
max_unmet_demand

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00386991, 0.01862374, 0.03193811, 0.06782089, 0.06066931,
        0.01574359, 0.00874462, 0.        , 0.01293673, 0.01790964,
        0.02861569, 0.00666261, 0.01387732, 0.03058289, 0.00284921,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00375901, 0.02137105, 0.02703659, 0.05930211, 0.06400893,
        0.0197787 , 0.00844001, 0.        , 0.01255431, 0.02024768,
        0.03052397, 0.00635689, 0.01377938, 0.02761642, 0.00329416,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00461788, 0.02132282, 0.03233055, 0.05967462, 0.0535676 ,
        0.01584881, 0.00752894, 0.        , 0.01313353, 0.02092016,
        0.0299041 , 0.0066235 , 0.01393671, 0.02841136, 0.00321705,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [23]:
column_names = ['max_unmet_demand_hour_1',
                'max_unmet_demand_hour_2',
                'max_unmet_demand_hour_3',
                'max_unmet_demand_hour_4',
                'max_unmet_demand_hour_5',
                'max_unmet_demand_hour_6',
                'max_unmet_demand_hour_7',
                'max_unmet_demand_hour_8',
                'max_unmet_demand_hour_9',
                'max_unmet_demand_hour_10',
                'max_unmet_demand_hour_11',
                'max_unmet_demand_hour_12',
                'max_unmet_demand_hour_13',
                'max_unmet_demand_hour_14',
                'max_unmet_demand_hour_15',
                'max_unmet_demand_hour_16',
                'max_unmet_demand_hour_17',
                'max_unmet_demand_hour_18',
                'max_unmet_demand_hour_19',
                'max_unmet_demand_hour_20',
                'max_unmet_demand_hour_21',
                'max_unmet_demand_hour_22',
                'max_unmet_demand_hour_23',
                'max_unmet_demand_hour_24',]

In [24]:
max_unmet_demand = pd.DataFrame(max_unmet_demand, columns=column_names)

In [25]:
max_unmet_demand

max_unmet_demand_hour_1  max_unmet_demand_hour_2  \
0                        0.0                      0.0   
1                        0.0                      0.0   
2                        0.0                      0.0   
3                        0.0                      0.0   
4                        0.0                      0.0   
..                       ...                      ...   
151                      0.0                      0.0   
152                      0.0                      0.0   
153                      0.0                      0.0   
154                      0.0                      0.0   
155                      0.0                      0.0   

     max_unmet_demand_hour_3  max_unmet_demand_hour_4  \
0                        0.0                      0.0   
1                        0.0                      0.0   
2                        0.0                      0.0   
3                        0.0                      0.0   
4                        0.0                      0.0   
..                       ...                      ...   
151                      0.0                      0.0   
152                      0.0                      0.0   
153                      0.0                      0.0   
154                      0.0                      0.0   
155                      0.0                      0.0   

     max_unmet_demand_hour_5  max_unmet_demand_hour_6  \
0                        0.0                 0.003870   
1                        0.0                 0.003759   
2                        0.0                 0.004618   
3                        0.0                 0.003787   
4                        0.0                 0.004356   
..                       ...                      ...   
151                      0.0                 0.004347   
152                      0.0                 0.003885   
153                      0.0                 0.004096   
154                      0.0                 0.004399   
155                      0.0                 0.004652   

     max_unmet_demand_hour_7  max_unmet_demand_hour_8  \
0                   0.018624                 0.031938   
1                   0.021371                 0.027037   
2                   0.021323                 0.032331   
3                   0.020126                 0.026651   
4                   0.019905                 0.029418   
..                       ...                      ...   
151                 0.022085                 0.026906   
152                 0.018486                 0.027276   
153                 0.022341                 0.028598   
154                 0.019921                 0.031811   
155                 0.018642                 0.026486   

     max_unmet_demand_hour_9  max_unmet_demand_hour_10  ...  \
0                   0.067821                  0.060669  ...   
1                   0.059302                  0.064009  ...   
2                   0.059675                  0.053568  ...   
3                   0.071984                  0.059494  ...   
4                   0.072691                  0.054307  ...   
..                       ...                       ...  ...   
151                 0.065552                  0.055720  ...   
152                 0.063678                  0.057930  ...   
153                 0.070199                  0.052590  ...   
154                 0.073320                  0.063121  ...   
155                 0.060855                  0.059104  ...   

     max_unmet_demand_hour_15  max_unmet_demand_hour_16  \
0                    0.017910                  0.028616   
1                    0.020248                  0.030524   
2                    0.020920                  0.029904   
3                    0.020459                  0.031991   
4                    0.018412                  0.028451   
..                        ...                       ...   
151                  0.018420                  0.028795   
152                  0.017297       

In [26]:
max_unmet_demand.to_excel('max_unmet_demand.xlsx', index=False)