In [1]:
import pandas as pd 
import numpy as np

In [2]:
from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)

In [3]:
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
ratios = pd.read_excel('ratios_per_household.xlsx')
demand_supply = pd.read_excel('Demand_Supply.xlsx')

In [4]:
# sum columns for each table
sum_max_hh_dd = max_hh_dd.sum()
sum_min_hh_dd = min_hh_dd.sum()

In [5]:
# Power supplied
ss_power = demand_supply['SS_Power']

In [6]:
hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

## Total Loss Max

In [7]:
sum_max_hh_dd.values

array([ 2.32000284,  2.1854947 ,  1.97468306,  2.45862135,  3.32336774,
        4.07009235,  7.17424938,  8.35041245, 16.90151425, 14.90945729,
       10.59417502,  9.12553079,  6.84790155, 11.04675339, 10.87769295,
       12.42037993,  9.35330303, 11.52157111, 12.84026514, 10.23134478,
        6.08890037,  4.5802809 ,  2.84020214,  2.84636513])

In [8]:
ss_power.values

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [9]:
total_loss_max = sum_max_hh_dd.values - ss_power.values

In [10]:
total_loss_max

array([-2.81199716, -2.2265053 , -1.84131694, -0.96937865, -0.01663226,
        0.65809235,  3.26624938,  4.55841245, 10.43351425,  9.07745729,
        2.76217502,  1.23353079, -0.55209845,  2.17875339,  2.98969295,
        4.82837993,  1.08530303,  2.13757111,  4.82426514,  0.46734478,
       -6.17909963, -6.4037191 , -5.69179786, -3.34163487])

In [11]:
new_total_loss_max = np.maximum(total_loss_max, np.zeros_like(total_loss_max))

In [12]:
new_total_loss_max

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.65809235,  3.26624938,  4.55841245, 10.43351425,  9.07745729,
        2.76217502,  1.23353079,  0.        ,  2.17875339,  2.98969295,
        4.82837993,  1.08530303,  2.13757111,  4.82426514,  0.46734478,
        0.        ,  0.        ,  0.        ,  0.        ])

## Total loss min

In [13]:
sum_min_hh_dd.values

array([ 1.73629914,  1.67500471,  1.70160429,  2.11973421,  2.31624109,
        3.0513202 ,  2.51534798,  5.83521829,  7.48697929,  8.23049991,
        5.42470836,  7.42006604,  5.95932768,  5.27180218,  7.85913904,
        8.71311713,  7.668663  , 10.12452073,  8.64237932,  4.73603721,
        4.61412439,  3.25995703,  2.65578999,  2.09959916])

In [14]:
ss_power.values

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [15]:
total_loss_min = sum_min_hh_dd.values - ss_power.values

In [16]:
total_loss_min

array([-3.39570086, -2.73699529, -2.11439571, -1.30826579, -1.02375891,
       -0.3606798 , -1.39265202,  2.04321829,  1.01897929,  2.39849991,
       -2.40729164, -0.47193396, -1.44067232, -3.59619782, -0.02886096,
        1.12111713, -0.599337  ,  0.74052073,  0.62637932, -5.02796279,
       -7.65387561, -7.72404297, -5.87621001, -4.08840084])

In [17]:
new_total_loss_min = np.maximum(total_loss_min, np.zeros_like(total_loss_min))

In [18]:
new_total_loss_min

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 2.04321829, 1.01897929, 2.39849991,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.12111713, 0.        , 0.74052073, 0.62637932, 0.        ,
       0.        , 0.        , 0.        , 0.        ])

## Power loss per household

In [19]:
ratios.values

array([[0.00620181, 0.0071648 , 0.00681386, 0.0065116 , 0.0058484 ,
        0.0058805 , 0.00570187, 0.00700641, 0.00650029, 0.00668351,
        0.00569971, 0.0070891 , 0.00692132, 0.00593768, 0.00599046,
        0.00592656, 0.00613894, 0.0064921 , 0.00633939, 0.00609659,
        0.00661769, 0.00584619, 0.00608112, 0.0062117 ],
       [0.00632693, 0.00690793, 0.00598925, 0.00638271, 0.00651605,
        0.00571198, 0.00654299, 0.00593114, 0.00568381, 0.00705142,
        0.00716055, 0.00684216, 0.00610932, 0.00576215, 0.0067725 ,
        0.00632178, 0.00585725, 0.00644628, 0.00572448, 0.00704868,
        0.00607158, 0.00664955, 0.00611118, 0.00644844],
       [0.00646603, 0.00597641, 0.0071819 , 0.00678101, 0.00704707,
        0.00701706, 0.00652823, 0.0070925 , 0.00571951, 0.00590117,
        0.0057378 , 0.00610357, 0.00623864, 0.006028  , 0.00699743,
        0.0061934 , 0.0061029 , 0.00651988, 0.00588926, 0.00688367,
        0.00578663, 0.00714777, 0.0068186 , 0.00595349],
       [0.005

In [20]:
min_power_loss_per_household = np.multiply(ratios.values, new_total_loss_min)

In [21]:
min_power_loss_per_household

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01431563, 0.00662366, 0.01603041,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00664437, 0.        , 0.00480753, 0.00397086, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01211862, 0.00579168, 0.01691282,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00708746, 0.        , 0.0047736 , 0.0035857 , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01449153, 0.00582807, 0.01415395,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00694353, 0.        , 0.00482811, 0.00368891, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [22]:
columns = ['min_power_loss_per_household_hour_1',
           'min_power_loss_per_household_hour_2',
           'min_power_loss_per_household_hour_3',
           'min_power_loss_per_household_hour_4',
           'min_power_loss_per_household_hour_5',
           'min_power_loss_per_household_hour_6',
           'min_power_loss_per_household_hour_7',
           'min_power_loss_per_household_hour_8',
           'min_power_loss_per_household_hour_9',
           'min_power_loss_per_household_hour_10',
           'min_power_loss_per_household_hour_11',
           'min_power_loss_per_household_hour_12',
           'min_power_loss_per_household_hour_13',
           'min_power_loss_per_household_hour_14',
           'min_power_loss_per_household_hour_15',
           'min_power_loss_per_household_hour_16',
           'min_power_loss_per_household_hour_17',
           'min_power_loss_per_household_hour_18',
           'min_power_loss_per_household_hour_19',
           'min_power_loss_per_household_hour_20',
           'min_power_loss_per_household_hour_21',
           'min_power_loss_per_household_hour_22',
           'min_power_loss_per_household_hour_23',
           'min_power_loss_per_household_hour_24',
           ]

In [23]:
min_power_loss_per_household = pd.DataFrame(min_power_loss_per_household, columns=columns)

In [24]:
min_power_loss_per_household

min_power_loss_per_household_hour_1  min_power_loss_per_household_hour_2  \
0                                    0.0                                  0.0   
1                                    0.0                                  0.0   
2                                    0.0                                  0.0   
3                                    0.0                                  0.0   
4                                    0.0                                  0.0   
..                                   ...                                  ...   
151                                  0.0                                  0.0   
152                                  0.0                                  0.0   
153                                  0.0                                  0.0   
154                                  0.0                                  0.0   
155                                  0.0                                  0.0   

     min_power_loss_per_household_hour_3  min_power_loss_per_household_hour_4  \
0                                    0.0                                  0.0   
1                                    0.0                                  0.0   
2                                    0.0                                  0.0   
3                                    0.0                                  0.0   
4                                    0.0                                  0.0   
..                                   ...                                  ...   
151                                  0.0                                  0.0   
152                                  0.0                                  0.0   
153                                  0.0                                  0.0   
154                                  0.0                                  0.0   
155                                  0.0                                  0.0   

     min_power_loss_per_household_hour_5  min_power_loss_per_household_hour_6  \
0                                    0.0                                  0.0   
1                                    0.0                                  0.0   
2                                    0.0                                  0.0   
3                                    0.0                                  0.0   
4                                    0.0                                  0.0   
..                                   ...                                  ...   
151                                  0.0                                  0.0   
152                                  0.0                                  0.0   
153                                  0.0                                  0.0   
154                                  0.0                                  0.0   
155                                  0.0                                  0.0   

     min_power_loss_per_household_hour_7  min_power_loss_per_household_hour_8  \
0                                    0.0                             0.014316   
1                                    0.0                             0.012119   
2                                    0.0                             0.014492   
3                                    0.0                             0.011946   
4                                    0.0                             0.013186   
..                                   ...                                  ...   
151                                  0.0                             0.012060   
152                                  0.0                             0.012226   
153                                  0.0                             0.012818   
154                                  0.0                             0.014259   
155                                  0.0                             0.011872   

     min_power_loss_per_household_hour_9  \
0                               0.006624   
1                        

In [25]:
min_power_loss_per_household.to_excel('min_power_loss_per_household.xlsx', index=False)

In [26]:
max_power_loss_per_household = np.multiply(ratios.values, new_total_loss_max)

In [28]:
max_power_loss_per_household

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00386991, 0.01862374, 0.03193811, 0.06782089, 0.06066931,
        0.01574359, 0.00874462, 0.        , 0.01293673, 0.01790964,
        0.02861569, 0.00666261, 0.01387732, 0.03058289, 0.00284921,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00375901, 0.02137105, 0.02703659, 0.05930211, 0.06400893,
        0.0197787 , 0.00844001, 0.        , 0.01255431, 0.02024768,
        0.03052397, 0.00635689, 0.01377938, 0.02761642, 0.00329416,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00461788, 0.02132282, 0.03233055, 0.05967462, 0.0535676 ,
        0.01584881, 0.00752894, 0.        , 0.01313353, 0.02092016,
        0.0299041 , 0.0066235 , 0.01393671, 0.02841136, 0.00321705,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [29]:
columns = ['max_power_loss_per_household_hour_1',
           'max_power_loss_per_household_hour_2',
           'max_power_loss_per_household_hour_3',
           'max_power_loss_per_household_hour_4',
           'max_power_loss_per_household_hour_5',
           'max_power_loss_per_household_hour_6',
           'max_power_loss_per_household_hour_7',
           'max_power_loss_per_household_hour_8',
           'max_power_loss_per_household_hour_9',
           'max_power_loss_per_household_hour_10',
           'max_power_loss_per_household_hour_11',
           'max_power_loss_per_household_hour_12',
           'max_power_loss_per_household_hour_13',
           'max_power_loss_per_household_hour_14',
           'max_power_loss_per_household_hour_15',
           'max_power_loss_per_household_hour_16',
           'max_power_loss_per_household_hour_17',
           'max_power_loss_per_household_hour_18',
           'max_power_loss_per_household_hour_19',
           'max_power_loss_per_household_hour_20',
           'max_power_loss_per_household_hour_21',
           'max_power_loss_per_household_hour_22',
           'max_power_loss_per_household_hour_23',
           'max_power_loss_per_household_hour_24',
           ]

In [30]:
max_power_loss_per_household = pd.DataFrame(max_power_loss_per_household, columns=columns)

In [31]:
max_power_loss_per_household

max_power_loss_per_household_hour_1  max_power_loss_per_household_hour_2  \
0                                    0.0                                  0.0   
1                                    0.0                                  0.0   
2                                    0.0                                  0.0   
3                                    0.0                                  0.0   
4                                    0.0                                  0.0   
..                                   ...                                  ...   
151                                  0.0                                  0.0   
152                                  0.0                                  0.0   
153                                  0.0                                  0.0   
154                                  0.0                                  0.0   
155                                  0.0                                  0.0   

     max_power_loss_per_household_hour_3  max_power_loss_per_household_hour_4  \
0                                    0.0                                  0.0   
1                                    0.0                                  0.0   
2                                    0.0                                  0.0   
3                                    0.0                                  0.0   
4                                    0.0                                  0.0   
..                                   ...                                  ...   
151                                  0.0                                  0.0   
152                                  0.0                                  0.0   
153                                  0.0                                  0.0   
154                                  0.0                                  0.0   
155                                  0.0                                  0.0   

     max_power_loss_per_household_hour_5  max_power_loss_per_household_hour_6  \
0                                    0.0                             0.003870   
1                                    0.0                             0.003759   
2                                    0.0                             0.004618   
3                                    0.0                             0.003787   
4                                    0.0                             0.004356   
..                                   ...                                  ...   
151                                  0.0                             0.004347   
152                                  0.0                             0.003885   
153                                  0.0                             0.004096   
154                                  0.0                             0.004399   
155                                  0.0                             0.004652   

     max_power_loss_per_household_hour_7  max_power_loss_per_household_hour_8  \
0                               0.018624                             0.031938   
1                               0.021371                             0.027037   
2                               0.021323                             0.032331   
3                               0.020126                             0.026651   
4                               0.019905                             0.029418   
..                                   ...                                  ...   
151                             0.022085                             0.026906   
152                             0.018486                             0.027276   
153                             0.022341                             0.028598   
154                             0.019921                             0.031811   
155                             0.018642                             0.026486   

     max_power_loss_per_household_hour_9  \
0                               0.067821   
1                        

In [32]:
max_power_loss_per_household.to_excel('max_power_loss_per_household.xlsx', index=False)

## Allocated Power CEL

In [34]:
min_allocated_power_cel = np.maximum(0, (min_hh_dd.values - min_power_loss_per_household))

In [37]:
columns = ['min_allocated_power_cel_hour_1',
           'min_allocated_power_cel_hour_2',
           'min_allocated_power_cel_hour_3',
           'min_allocated_power_cel_hour_4',
           'min_allocated_power_cel_hour_5',
           'min_allocated_power_cel_hour_6',
           'min_allocated_power_cel_hour_7',
           'min_allocated_power_cel_hour_8',
           'min_allocated_power_cel_hour_9',
           'min_allocated_power_cel_hour_10',
           'min_allocated_power_cel_hour_11',
           'min_allocated_power_cel_hour_12',
           'min_allocated_power_cel_hour_13',
           'min_allocated_power_cel_hour_14',
           'min_allocated_power_cel_hour_15',
           'min_allocated_power_cel_hour_16',
           'min_allocated_power_cel_hour_17',
           'min_allocated_power_cel_hour_18',
           'min_allocated_power_cel_hour_19',
           'min_allocated_power_cel_hour_20',
           'min_allocated_power_cel_hour_21',
           'min_allocated_power_cel_hour_22',
           'min_allocated_power_cel_hour_23',
           'min_allocated_power_cel_hour_24']

In [38]:
min_allocated_power_cel = pd.DataFrame(min_allocated_power_cel.values, columns=columns)

In [39]:
min_allocated_power_cel

min_allocated_power_cel_hour_1  min_allocated_power_cel_hour_2  \
0                          0.010768                        0.012001   
1                          0.010985                        0.011571   
2                          0.011227                        0.010011   
3                          0.009785                        0.011650   
4                          0.011163                        0.010641   
..                              ...                             ...   
151                        0.010435                        0.010214   
152                        0.011361                        0.012128   
153                        0.011701                        0.009820   
154                        0.012332                        0.011266   
155                        0.010685                        0.011699   

     min_allocated_power_cel_hour_3  min_allocated_power_cel_hour_4  \
0                          0.011594                        0.013803   
1                          0.010191                        0.013530   
2                          0.012221                        0.014374   
3                          0.011528                        0.014225   
4                          0.009732                        0.012215   
..                              ...                             ...   
151                        0.009667                        0.014683   
152                        0.011693                        0.013153   
153                        0.011268                        0.012775   
154                        0.012125                        0.012725   
155                        0.012131                        0.012467   

     min_allocated_power_cel_hour_5  min_allocated_power_cel_hour_6  \
0                          0.013546                        0.017943   
1                          0.015093                        0.017429   
2                          0.016323                        0.021411   
3                          0.015727                        0.017559   
4                          0.013105                        0.020198   
..                              ...                             ...   
151                        0.015802                        0.020156   
152                        0.015926                        0.018012   
153                        0.013608                        0.018994   
154                        0.015160                        0.020396   
155                        0.014313                        0.021570   

     min_allocated_power_cel_hour_7  min_allocated_power_cel_hour_8  \
0                          0.014342                        0.026568   
1                          0.016458                        0.022491   
2                          0.016421                        0.026895   
3                          0.015499                        0.022171   
4                          0.015329                        0.024472   
..                              ...                             ...   
151                        0.017007                        0.022383   
152                        0.014236                        0.022690   
153                        0.017205                        0.023790   
154                        0.015341                        0.026462   
155                        0.014357                        0.022033   

     min_allocated_power_cel_hour_9  min_allocated_power_cel_hour_10  ...  \
0                          0.042044                         0.038978  ...   
1                          0.036763                         0.041124  ...   
2                          0.036994                         0.034416  ...   
3                          0.044625                         0.038223  ...   
4                          0.045063                         0.034891  ...   
..                              ...                              ...  ...   
151                        0.040637                   

In [40]:
min_allocated_power_cel.to_excel('min_allocated_power_cel.xlsx', index=False)

max

In [41]:
max_allocated_power_cel = np.maximum(0, (max_hh_dd.values - max_power_loss_per_household))

In [42]:
columns = ['max_allocated_power_cel_hour_1',
           'max_allocated_power_cel_hour_2',
           'max_allocated_power_cel_hour_3',
           'max_allocated_power_cel_hour_4',
           'max_allocated_power_cel_hour_5',
           'max_allocated_power_cel_hour_6',
           'max_allocated_power_cel_hour_7',
           'max_allocated_power_cel_hour_8',
           'max_allocated_power_cel_hour_9',
           'max_allocated_power_cel_hour_10',
           'max_allocated_power_cel_hour_11',
           'max_allocated_power_cel_hour_12',
           'max_allocated_power_cel_hour_13',
           'max_allocated_power_cel_hour_14',
           'max_allocated_power_cel_hour_15',
           'max_allocated_power_cel_hour_16',
           'max_allocated_power_cel_hour_17',
           'max_allocated_power_cel_hour_18',
           'max_allocated_power_cel_hour_19',
           'max_allocated_power_cel_hour_20',
           'max_allocated_power_cel_hour_21',
           'max_allocated_power_cel_hour_22',
           'max_allocated_power_cel_hour_23',
           'max_allocated_power_cel_hour_24']

In [43]:
max_allocated_power_cel = pd.DataFrame(max_allocated_power_cel.values, columns=columns)

In [44]:
max_allocated_power_cel

max_allocated_power_cel_hour_1  max_allocated_power_cel_hour_2  \
0                          0.014388                        0.015659   
1                          0.014678                        0.015097   
2                          0.015001                        0.013061   
3                          0.013074                        0.015200   
4                          0.014916                        0.013884   
..                              ...                             ...   
151                        0.013944                        0.013327   
152                        0.015180                        0.015824   
153                        0.015635                        0.012813   
154                        0.016478                        0.014699   
155                        0.014277                        0.015265   

     max_allocated_power_cel_hour_3  max_allocated_power_cel_hour_4  \
0                          0.013455                        0.016010   
1                          0.011827                        0.015693   
2                          0.014182                        0.016672   
3                          0.013378                        0.016499   
4                          0.011294                        0.014167   
..                              ...                             ...   
151                        0.011218                        0.017031   
152                        0.013570                        0.015256   
153                        0.013077                        0.014817   
154                        0.014071                        0.014759   
155                        0.014078                        0.014460   

     max_allocated_power_cel_hour_5  max_allocated_power_cel_hour_6  \
0                          0.019436                        0.020064   
1                          0.021655                        0.019489   
2                          0.023420                        0.023942   
3                          0.022565                        0.019634   
4                          0.018803                        0.022586   
..                              ...                             ...   
151                        0.022673                        0.022538   
152                        0.022851                        0.020141   
153                        0.019525                        0.021239   
154                        0.021752                        0.022807   
155                        0.020537                        0.024120   

     max_allocated_power_cel_hour_7  max_allocated_power_cel_hour_8  \
0                          0.022283                        0.026568   
1                          0.025570                        0.022491   
2                          0.025512                        0.026895   
3                          0.024080                        0.022171   
4                          0.023816                        0.024472   
..                              ...                             ...   
151                        0.026424                        0.022383   
152                        0.022118                        0.022690   
153                        0.026730                        0.023790   
154                        0.023835                        0.026462   
155                        0.022305                        0.022033   

     max_allocated_power_cel_hour_9  max_allocated_power_cel_hour_10  ...  \
0                          0.042044                         0.038978  ...   
1                          0.036763                         0.041124  ...   
2                          0.036994                         0.034416  ...   
3                          0.044625                         0.038223  ...   
4                          0.045063                         0.034891  ...   
..                              ...                              ...  ...   
151                        0.040637                   

In [45]:
max_allocated_power_cel.to_excel('max_allocated_power_cel.xlsx', index=False)