In [73]:
import pandas as pd
import numpy as np

In [74]:
avg_hh_dd = pd.read_excel('avg_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
demand_supply = pd.read_excel('Demand_Supply.xlsx')

In [75]:
avg_hh_dd.values

array([[0.01299518, 0.01387844, 0.01243753, ..., 0.02338703, 0.01675449,
        0.01516877],
       [0.01325735, 0.01338088, 0.01093236, ..., 0.02660079, 0.0168373 ,
        0.01574688],
       [0.01354882, 0.0115765 , 0.01310933, ..., 0.02859386, 0.01878637,
        0.01453823],
       ...,
       [0.01412085, 0.0113563 , 0.01208783, ..., 0.02397034, 0.01697854,
        0.01390405],
       [0.01488262, 0.01302829, 0.01300647, ..., 0.02301496, 0.01739208,
        0.01477267],
       [0.012895  , 0.01352935, 0.01301291, ..., 0.02755249, 0.01872205,
        0.01399997]])

In [76]:
min_power_allocation_threshold_per_hh = np.multiply(avg_hh_dd, 0.5)

## min_power_allocation = 0.5 * D_i
## SS_power >= sum(min_power_allocation)

In [77]:
min_power_allocation_threshold_per_hh.values

array([[0.00649759, 0.00693922, 0.00621876, ..., 0.01169352, 0.00837724,
        0.00758438],
       [0.00662867, 0.00669044, 0.00546618, ..., 0.0133004 , 0.00841865,
        0.00787344],
       [0.00677441, 0.00578825, 0.00655467, ..., 0.01429693, 0.00939318,
        0.00726911],
       ...,
       [0.00706042, 0.00567815, 0.00604392, ..., 0.01198517, 0.00848927,
        0.00695203],
       [0.00744131, 0.00651414, 0.00650323, ..., 0.01150748, 0.00869604,
        0.00738633],
       [0.0064475 , 0.00676467, 0.00650646, ..., 0.01377625, 0.00936103,
        0.00699998]])

In [78]:
sum_min_power_allocation = min_power_allocation_threshold_per_hh.sum()

In [79]:
sum_min_power_allocation.values

array([1.04769275, 0.96851561, 0.91266447, 1.12816868, 1.36917139,
       1.793472  , 2.23904018, 3.51134512, 6.07837644, 5.56481721,
       3.81722248, 4.17496705, 3.21385093, 4.06933873, 4.69986428,
       5.25687653, 4.28031443, 5.45733134, 5.29317231, 3.86171155,
       2.71605434, 2.00019426, 1.3775816 , 1.22098362])

In [80]:
ss_power = demand_supply['SS_Power'].values

In [81]:
ss_power

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [82]:
print(ss_power >= sum_min_power_allocation.values)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]


In [83]:
columns_avg = ['min_power_allocation_threshold_hour_1',
                'min_power_allocation_threshold_hour_2',
                'min_power_allocation_threshold_hour_3',
                'min_power_allocation_threshold_hour_4',
                'min_power_allocation_threshold_hour_5',
                'min_power_allocation_threshold_hour_6',
                'min_power_allocation_threshold_hour_7',
                'min_power_allocation_threshold_hour_8',
                'min_power_allocation_threshold_hour_9',
                'min_power_allocation_threshold_hour_10',
                'min_power_allocation_threshold_hour_11',
                'min_power_allocation_threshold_hour_12',
                'min_power_allocation_threshold_hour_13',
                'min_power_allocation_threshold_hour_14',
                'min_power_allocation_threshold_hour_15',
                'min_power_allocation_threshold_hour_16',
                'min_power_allocation_threshold_hour_17',
                'min_power_allocation_threshold_hour_18',
                'min_power_allocation_threshold_hour_19',
                'min_power_allocation_threshold_hour_20',
                'min_power_allocation_threshold_hour_21',
                'min_power_allocation_threshold_hour_22',
                'min_power_allocation_threshold_hour_23',
                'min_power_allocation_threshold_hour_24']



In [84]:
min_power_allocation_threshold_per_hh.values

array([[0.00649759, 0.00693922, 0.00621876, ..., 0.01169352, 0.00837724,
        0.00758438],
       [0.00662867, 0.00669044, 0.00546618, ..., 0.0133004 , 0.00841865,
        0.00787344],
       [0.00677441, 0.00578825, 0.00655467, ..., 0.01429693, 0.00939318,
        0.00726911],
       ...,
       [0.00706042, 0.00567815, 0.00604392, ..., 0.01198517, 0.00848927,
        0.00695203],
       [0.00744131, 0.00651414, 0.00650323, ..., 0.01150748, 0.00869604,
        0.00738633],
       [0.0064475 , 0.00676467, 0.00650646, ..., 0.01377625, 0.00936103,
        0.00699998]])

In [85]:

min_power_allocation_threshold_per_hh = pd.DataFrame(min_power_allocation_threshold_per_hh.values, columns=columns_avg)

In [86]:
min_power_allocation_threshold_per_hh

min_power_allocation_threshold_hour_1  \
0                                 0.006498   
1                                 0.006629   
2                                 0.006774   
3                                 0.005904   
4                                 0.006736   
..                                     ...   
151                               0.006297   
152                               0.006855   
153                               0.007060   
154                               0.007441   
155                               0.006447   

     min_power_allocation_threshold_hour_2  \
0                                 0.006939   
1                                 0.006690   
2                                 0.005788   
3                                 0.006736   
4                                 0.006153   
..                                     ...   
151                               0.005906   
152                               0.007013   
153                               0.005678   
154                               0.006514   
155                               0.006765   

     min_power_allocation_threshold_hour_3  \
0                                 0.006219   
1                                 0.005466   
2                                 0.006555   
3                                 0.006183   
4                                 0.005220   
..                                     ...   
151                               0.005185   
152                               0.006272   
153                               0.006044   
154                               0.006503   
155                               0.006506   

     min_power_allocation_threshold_hour_4  \
0                                 0.007346   
1                                 0.007201   
2                                 0.007650   
3                                 0.007571   
4                                 0.006501   
..                                     ...   
151                               0.007815   
152                               0.007000   
153                               0.006799   
154                               0.006772   
155                               0.006635   

     min_power_allocation_threshold_hour_5  \
0                                 0.008007   
1                                 0.008922   
2                                 0.009649   
3                                 0.009296   
4                                 0.007746   
..                                     ...   
151                               0.009341   
152                               0.009414   
153                               0.008044   
154                               0.008961   
155                               0.008461   

     min_power_allocation_threshold_hour_6  \
0                                 0.010547   
1                                 0.010244   
2                                 0.012585   
3                                 0.010320   
4                                 0.011872   
..                                     ...   
151                               0.011847   
152                               0.010587   
153                               0.011164   
154                               0.011988   
155                               0.012678   

     min_power_allocation_threshold_hour_7  \
0                                 0.012767   
1                                 0.014650   
2                                 0.014617   
3                                 0.013796   
4                                 0.013645   
..                                     ...   
151                               0.015139   
152                               0.012672   
153                               0.015315   
154                               0.013656   
155                               0.012779   

     min_power_allocation_threshold_hour_8  \
0                                 0.024602   
1                                 0.020826

In [87]:
min_power_allocation_threshold_per_hh.to_excel('min_power_allocation_threshold_per_hh.xlsx', index=False)

In [89]:

balance_power = ss_power - sum_min_power_allocation.values

In [90]:
balance_power

array([4.08430725, 3.44348439, 2.90333553, 2.29983132, 1.97082861,
       1.618528  , 1.66895982, 0.28065488, 0.38962356, 0.26718279,
       4.01477752, 3.71703295, 4.18614907, 4.79866127, 3.18813572,
       2.33512347, 3.98768557, 3.92666866, 2.72282769, 5.90228845,
       9.55194566, 8.98380574, 7.1544184 , 4.96701638])

In [91]:
hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [93]:
balance_power_df = pd.DataFrame({'Hour': hours, 'Balance_Power': balance_power})

In [94]:

balance_power_df.to_excel('balance_power.xlsx', index=False)

## New power allocated cea

In [96]:
ratios = pd.read_excel('ratios_per_household.xlsx')

In [97]:
ratios.values

array([[0.00620181, 0.0071648 , 0.00681386, ..., 0.00584619, 0.00608112,
        0.0062117 ],
       [0.00632693, 0.00690793, 0.00598925, ..., 0.00664955, 0.00611118,
        0.00644844],
       [0.00646603, 0.00597641, 0.0071819 , ..., 0.00714777, 0.0068186 ,
        0.00595349],
       ...,
       [0.00673902, 0.00586273, 0.00662228, ..., 0.005992  , 0.00616244,
        0.00569379],
       [0.00710257, 0.0067259 , 0.00712555, ..., 0.00575318, 0.00631254,
        0.00604949],
       [0.006154  , 0.00698458, 0.00712908, ..., 0.00688745, 0.00679526,
        0.00573307]])

In [95]:
balance_power

array([4.08430725, 3.44348439, 2.90333553, 2.29983132, 1.97082861,
       1.618528  , 1.66895982, 0.28065488, 0.38962356, 0.26718279,
       4.01477752, 3.71703295, 4.18614907, 4.79866127, 3.18813572,
       2.33512347, 3.98768557, 3.92666866, 2.72282769, 5.90228845,
       9.55194566, 8.98380574, 7.1544184 , 4.96701638])

In [98]:

ratio_times_balance_power = np.multiply(ratios.values, balance_power)

In [99]:
ratio_times_balance_power

array([[0.02533009, 0.02467187, 0.01978291, ..., 0.05252104, 0.0435069 ,
        0.03085361],
       [0.02584111, 0.02378736, 0.01738881, ..., 0.05973829, 0.04372193,
        0.0320295 ],
       [0.02640924, 0.02057968, 0.02085147, ..., 0.06421418, 0.04878315,
        0.02957108],
       ...,
       [0.02752423, 0.02018823, 0.01922669, ..., 0.053831  , 0.04408869,
        0.02828116],
       [0.02900907, 0.02316055, 0.02068785, ..., 0.05168545, 0.04516256,
        0.03004794],
       [0.02513482, 0.02405129, 0.02069811, ..., 0.06187555, 0.04861614,
        0.02847625]])

In [102]:
min_power_allocation_threshold_per_hh.values

array([[0.00649759, 0.00693922, 0.00621876, ..., 0.01169352, 0.00837724,
        0.00758438],
       [0.00662867, 0.00669044, 0.00546618, ..., 0.0133004 , 0.00841865,
        0.00787344],
       [0.00677441, 0.00578825, 0.00655467, ..., 0.01429693, 0.00939318,
        0.00726911],
       ...,
       [0.00706042, 0.00567815, 0.00604392, ..., 0.01198517, 0.00848927,
        0.00695203],
       [0.00744131, 0.00651414, 0.00650323, ..., 0.01150748, 0.00869604,
        0.00738633],
       [0.0064475 , 0.00676467, 0.00650646, ..., 0.01377625, 0.00936103,
        0.00699998]])

In [100]:
x = min_power_allocation_threshold_per_hh.values + ratio_times_balance_power

In [101]:
x

array([[0.03182767, 0.03161109, 0.02600167, ..., 0.06421456, 0.05188414,
        0.03843799],
       [0.03246979, 0.0304778 , 0.02285499, ..., 0.07303868, 0.05214058,
        0.03990294],
       [0.03318365, 0.02636793, 0.02740614, ..., 0.07851111, 0.05817633,
        0.03684019],
       ...,
       [0.03458466, 0.02586637, 0.0252706 , ..., 0.06581617, 0.05257796,
        0.03523319],
       [0.03645038, 0.02967469, 0.02719109, ..., 0.06319293, 0.05385861,
        0.03743427],
       [0.03158232, 0.03081597, 0.02720456, ..., 0.07565179, 0.05797716,
        0.03547624]])

In [103]:
x_max = np.maximum(min_power_allocation_threshold_per_hh.values, x)

In [104]:
x_max

array([[0.03182767, 0.03161109, 0.02600167, ..., 0.06421456, 0.05188414,
        0.03843799],
       [0.03246979, 0.0304778 , 0.02285499, ..., 0.07303868, 0.05214058,
        0.03990294],
       [0.03318365, 0.02636793, 0.02740614, ..., 0.07851111, 0.05817633,
        0.03684019],
       ...,
       [0.03458466, 0.02586637, 0.0252706 , ..., 0.06581617, 0.05257796,
        0.03523319],
       [0.03645038, 0.02967469, 0.02719109, ..., 0.06319293, 0.05385861,
        0.03743427],
       [0.03158232, 0.03081597, 0.02720456, ..., 0.07565179, 0.05797716,
        0.03547624]])

In [105]:

min_power_allocated_cea = np.minimum(min_hh_dd.values, x_max)
max_power_allocated_cea = np.minimum(max_hh_dd.values, x_max)

In [106]:
min_power_allocated_cea

array([[0.01076819, 0.01200107, 0.01159449, ..., 0.01905833, 0.01615019,
        0.01304208],
       [0.01098544, 0.01157082, 0.01019134, ..., 0.02167726, 0.01623001,
        0.01353914],
       [0.01122696, 0.01001052, 0.01222076, ..., 0.02330142, 0.01810878,
        0.01249994],
       ...,
       [0.01170096, 0.0098201 , 0.01126849, ..., 0.01953368, 0.01636615,
        0.01195468],
       [0.01233218, 0.01126592, 0.01212486, ..., 0.01875512, 0.01676479,
        0.01270151],
       [0.01068518, 0.0116992 , 0.01213087, ..., 0.0224528 , 0.01804679,
        0.01203715]])

In [107]:
max_power_allocated_cea

array([[0.01438821, 0.01565863, 0.01345521, ..., 0.0267772 , 0.01727162,
        0.01768076],
       [0.01467849, 0.01509725, 0.01182687, ..., 0.03045682, 0.01735698,
        0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, ..., 0.0327388 , 0.01936621,
        0.0169458 ],
       ...,
       [0.01563455, 0.01281297, 0.01307689, ..., 0.02744506, 0.01750258,
        0.01620661],
       [0.01647798, 0.01469943, 0.0140707 , ..., 0.02635118, 0.01792889,
        0.01721907],
       [0.01427729, 0.01526476, 0.01407767, ..., 0.03154647, 0.01929991,
        0.01631841]])

In [108]:
columns_min_cea = ['min_power_allocated_cea_hour_1',
                   'min_power_allocated_cea_hour_2',
                   'min_power_allocated_cea_hour_3',
                   'min_power_allocated_cea_hour_4',
                   'min_power_allocated_cea_hour_5',
                   'min_power_allocated_cea_hour_6',
                   'min_power_allocated_cea_hour_7',
                   'min_power_allocated_cea_hour_8',
                   'min_power_allocated_cea_hour_9',
                   'min_power_allocated_cea_hour_10',
                   'min_power_allocated_cea_hour_11',
                   'min_power_allocated_cea_hour_12',
                   'min_power_allocated_cea_hour_13',
                   'min_power_allocated_cea_hour_14',
                   'min_power_allocated_cea_hour_15',
                   'min_power_allocated_cea_hour_16',
                   'min_power_allocated_cea_hour_17',
                   'min_power_allocated_cea_hour_18',
                   'min_power_allocated_cea_hour_19',
                   'min_power_allocated_cea_hour_20',
                   'min_power_allocated_cea_hour_21',
                   'min_power_allocated_cea_hour_22',
                   'min_power_allocated_cea_hour_23',
                   'min_power_allocated_cea_hour_24',]

columns_max_cea = ['max_power_allocated_cea_hour_1',
                   'max_power_allocated_cea_hour_2',
                   'max_power_allocated_cea_hour_3',
                   'max_power_allocated_cea_hour_4',
                   'max_power_allocated_cea_hour_5',
                   'max_power_allocated_cea_hour_6',
                   'max_power_allocated_cea_hour_7',
                   'max_power_allocated_cea_hour_8',
                   'max_power_allocated_cea_hour_9',
                   'max_power_allocated_cea_hour_10',
                   'max_power_allocated_cea_hour_11',
                   'max_power_allocated_cea_hour_12',
                   'max_power_allocated_cea_hour_13',
                   'max_power_allocated_cea_hour_14',
                   'max_power_allocated_cea_hour_15',
                   'max_power_allocated_cea_hour_16',
                   'max_power_allocated_cea_hour_17',
                   'max_power_allocated_cea_hour_18',
                   'max_power_allocated_cea_hour_19',
                   'max_power_allocated_cea_hour_20',
                   'max_power_allocated_cea_hour_21',
                   'max_power_allocated_cea_hour_22',
                   'max_power_allocated_cea_hour_23',
                   'max_power_allocated_cea_hour_24',]

In [109]:
power_allocated_cea_min = pd.DataFrame(min_power_allocated_cea, columns=columns_min_cea)
power_allocated_cea_max = pd.DataFrame(max_power_allocated_cea, columns=columns_max_cea)

In [110]:
power_allocated_cea_min.to_excel('power_allocated_cea_min.xlsx', index=False)
power_allocated_cea_max.to_excel('power_allocated_cea_max.xlsx', index=False)

In [111]:
unmet_demand_cea_min = min_hh_dd.values - power_allocated_cea_min.values
unmet_demand_cea_max = max_hh_dd.values - power_allocated_cea_max.values

In [112]:
column_min = ['min_unmet_demand_cea_hour_1',
                'min_unmet_demand_cea_hour_2',
                'min_unmet_demand_cea_hour_3',
                'min_unmet_demand_cea_hour_4',
                'min_unmet_demand_cea_hour_5',
                'min_unmet_demand_cea_hour_6',
                'min_unmet_demand_cea_hour_7',
                'min_unmet_demand_cea_hour_8',
                'min_unmet_demand_cea_hour_9',
                'min_unmet_demand_cea_hour_10',
                'min_unmet_demand_cea_hour_11',
                'min_unmet_demand_cea_hour_12',
                'min_unmet_demand_cea_hour_13',
                'min_unmet_demand_cea_hour_14',
                'min_unmet_demand_cea_hour_15',
                'min_unmet_demand_cea_hour_16',
                'min_unmet_demand_cea_hour_17',
                'min_unmet_demand_cea_hour_18',
                'min_unmet_demand_cea_hour_19',
                'min_unmet_demand_cea_hour_20',
                'min_unmet_demand_cea_hour_21',
                'min_unmet_demand_cea_hour_22',
                'min_unmet_demand_cea_hour_23',
                'min_unmet_demand_cea_hour_24']


column_max = ['max_unmet_demand_cea_hour_1',
                'max_unmet_demand_cea_hour_2',
                'max_unmet_demand_cea_hour_3',
                'max_unmet_demand_cea_hour_4',
                'max_unmet_demand_cea_hour_5',
                'max_unmet_demand_cea_hour_6',
                'max_unmet_demand_cea_hour_7',
                'max_unmet_demand_cea_hour_8',
                'max_unmet_demand_cea_hour_9',
                'max_unmet_demand_cea_hour_10',
                'max_unmet_demand_cea_hour_11',
                'max_unmet_demand_cea_hour_12',
                'max_unmet_demand_cea_hour_13',
                'max_unmet_demand_cea_hour_14',
                'max_unmet_demand_cea_hour_15',
                'max_unmet_demand_cea_hour_16',
                'max_unmet_demand_cea_hour_17',
                'max_unmet_demand_cea_hour_18',
                'max_unmet_demand_cea_hour_19',
                'max_unmet_demand_cea_hour_20',
                'max_unmet_demand_cea_hour_21',
                'max_unmet_demand_cea_hour_22',
                'max_unmet_demand_cea_hour_23',
                'max_unmet_demand_cea_hour_24']


In [113]:
unmet_demand_cea_min = pd.DataFrame(unmet_demand_cea_min, columns=column_min)
unmet_demand_cea_max = pd.DataFrame(unmet_demand_cea_max, columns=column_max)

In [114]:
unmet_demand_cea_min.to_excel('unmet_demand_cea_min.xlsx', index=False)
unmet_demand_cea_max.to_excel('unmet_demand_cea_max.xlsx', index=False)