In [35]:
import pandas as pd
import numpy as np

In [36]:
from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)


In [37]:
demand_supply = pd.read_excel('Demand_Supply.xlsx')
avg_hh_dd = pd.read_excel('avg_hh_demand_reformatted.xlsx')
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')

## Dividing SS_Power by 156 (number of households)

In [38]:
ss_power = demand_supply['SS_Power'].values

In [39]:
ss_power

array([ 5.132,  4.412,  3.816,  3.428,  3.34 ,  3.412,  3.908,  3.792,
        6.468,  5.832,  7.832,  7.892,  7.4  ,  8.868,  7.888,  7.592,
        8.268,  9.384,  8.016,  9.764, 12.268, 10.984,  8.532,  6.188])

In [40]:
ss_power_over_n = ss_power/156

In [41]:
ss_power_over_n

array([0.03289744, 0.02828205, 0.02446154, 0.02197436, 0.02141026,
       0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
       0.05020513, 0.05058974, 0.0474359 , 0.05684615, 0.0505641 ,
       0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
       0.07864103, 0.07041026, 0.05469231, 0.03966667])

## Getting the minimum value between min_hh_dd and ss_power_over_n 

In [42]:
min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.04088393, 0.04866755, 0.05500866,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.05163881, 0.04707744, 0.06572936, 0.0547874 , 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.03460951, 0.04255457, 0.05803668,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.05508243, 0.0449173 , 0.06526549, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.0413863 , 0.04282187, 0.04856956,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.05396384, 0.04680111, 0.06601068, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [43]:
ss_power_over_n

array([0.03289744, 0.02828205, 0.02446154, 0.02197436, 0.02141026,
       0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
       0.05020513, 0.05058974, 0.0474359 , 0.05684615, 0.0505641 ,
       0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
       0.07864103, 0.07041026, 0.05469231, 0.03966667])

In [44]:
power_allocated_cea_using_min_hh_dd = np.minimum(min_hh_dd.values, ss_power_over_n)

In [50]:
power_allocated_cea_using_min_hh_dd

power_allocated_cea_from_min_hour_1  power_allocated_cea_from_min_hour_2  \
0                               0.010768                             0.012001   
1                               0.010985                             0.011571   
2                               0.011227                             0.010011   
3                               0.009785                             0.011650   
4                               0.011163                             0.010641   
..                                   ...                                  ...   
151                             0.010435                             0.010214   
152                             0.011361                             0.012128   
153                             0.011701                             0.009820   
154                             0.012332                             0.011266   
155                             0.010685                             0.011699   

     power_allocated_cea_from_min_hour_3  power_allocated_cea_from_min_hour_4  \
0                               0.011594                             0.013803   
1                               0.010191                             0.013530   
2                               0.012221                             0.014374   
3                               0.011528                             0.014225   
4                               0.009732                             0.012215   
..                                   ...                                  ...   
151                             0.009667                             0.014683   
152                             0.011693                             0.013153   
153                             0.011268                             0.012775   
154                             0.012125                             0.012725   
155                             0.012131                             0.012467   

     power_allocated_cea_from_min_hour_5  power_allocated_cea_from_min_hour_6  \
0                               0.013546                             0.017943   
1                               0.015093                             0.017429   
2                               0.016323                             0.021411   
3                               0.015727                             0.017559   
4                               0.013105                             0.020198   
..                                   ...                                  ...   
151                             0.015802                             0.020156   
152                             0.015926                             0.018012   
153                             0.013608                             0.018994   
154                             0.015160                             0.020396   
155                             0.014313                             0.021570   

     power_allocated_cea_from_min_hour_7  power_allocated_cea_from_min_hour_8  \
0                               0.014342                             0.024308   
1                               0.016458                             0.024308   
2                               0.016421                             0.024308   
3                               0.015499                             0.024308   
4                               0.015329                             0.024308   
..                                   ...                                  ...   
151                             0.017007                             0.024308   
152                             0.014236                             0.024308   
153                             0.017205                             0.024308   
154                             0.015341                             0.024308   
155                             0.014357                             0.024308   

     power_allocated_cea_from_min_hour_9  \
0                               0.041462   
1                        

In [51]:
power_allocated_cea_using_min_hh_dd_columns = ['power_allocated_cea_from_min_hour_1',
                                               'power_allocated_cea_from_min_hour_2',
                                               'power_allocated_cea_from_min_hour_3',
                                               'power_allocated_cea_from_min_hour_4',
                                               'power_allocated_cea_from_min_hour_5',
                                               'power_allocated_cea_from_min_hour_6',
                                               'power_allocated_cea_from_min_hour_7',
                                               'power_allocated_cea_from_min_hour_8',
                                               'power_allocated_cea_from_min_hour_9',
                                               'power_allocated_cea_from_min_hour_10',
                                               'power_allocated_cea_from_min_hour_11',
                                               'power_allocated_cea_from_min_hour_12',
                                               'power_allocated_cea_from_min_hour_13',
                                               'power_allocated_cea_from_min_hour_14',
                                               'power_allocated_cea_from_min_hour_15',
                                               'power_allocated_cea_from_min_hour_16',
                                               'power_allocated_cea_from_min_hour_17',
                                               'power_allocated_cea_from_min_hour_18',
                                               'power_allocated_cea_from_min_hour_19',
                                               'power_allocated_cea_from_min_hour_20',
                                               'power_allocated_cea_from_min_hour_21',
                                               'power_allocated_cea_from_min_hour_22',
                                               'power_allocated_cea_from_min_hour_23',
                                               'power_allocated_cea_from_min_hour_24']

In [52]:
power_allocated_cea_using_min_hh_dd = pd.DataFrame(power_allocated_cea_using_min_hh_dd, columns=power_allocated_cea_using_min_hh_dd_columns)

In [53]:
power_allocated_cea_using_min_hh_dd

power_allocated_cea_from_min_hour_1  power_allocated_cea_from_min_hour_2  \
0                               0.010768                             0.012001   
1                               0.010985                             0.011571   
2                               0.011227                             0.010011   
3                               0.009785                             0.011650   
4                               0.011163                             0.010641   
..                                   ...                                  ...   
151                             0.010435                             0.010214   
152                             0.011361                             0.012128   
153                             0.011701                             0.009820   
154                             0.012332                             0.011266   
155                             0.010685                             0.011699   

     power_allocated_cea_from_min_hour_3  power_allocated_cea_from_min_hour_4  \
0                               0.011594                             0.013803   
1                               0.010191                             0.013530   
2                               0.012221                             0.014374   
3                               0.011528                             0.014225   
4                               0.009732                             0.012215   
..                                   ...                                  ...   
151                             0.009667                             0.014683   
152                             0.011693                             0.013153   
153                             0.011268                             0.012775   
154                             0.012125                             0.012725   
155                             0.012131                             0.012467   

     power_allocated_cea_from_min_hour_5  power_allocated_cea_from_min_hour_6  \
0                               0.013546                             0.017943   
1                               0.015093                             0.017429   
2                               0.016323                             0.021411   
3                               0.015727                             0.017559   
4                               0.013105                             0.020198   
..                                   ...                                  ...   
151                             0.015802                             0.020156   
152                             0.015926                             0.018012   
153                             0.013608                             0.018994   
154                             0.015160                             0.020396   
155                             0.014313                             0.021570   

     power_allocated_cea_from_min_hour_7  power_allocated_cea_from_min_hour_8  \
0                               0.014342                             0.024308   
1                               0.016458                             0.024308   
2                               0.016421                             0.024308   
3                               0.015499                             0.024308   
4                               0.015329                             0.024308   
..                                   ...                                  ...   
151                             0.017007                             0.024308   
152                             0.014236                             0.024308   
153                             0.017205                             0.024308   
154                             0.015341                             0.024308   
155                             0.014357                             0.024308   

     power_allocated_cea_from_min_hour_9  \
0                               0.041462   
1                        

In [54]:
power_allocated_cea_using_min_hh_dd.to_excel('power_allocated_cea_using_min_hh_dd.xlsx', index=False)

## Getting the minimum value between max_hh_dd and ss_power_over_n 

In [55]:
max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02393417, 0.04090667, 0.05850642, 0.10986478, 0.09964756,
        0.06038371, 0.0646918 , 0.04739652, 0.06559203, 0.06516239,
        0.07361013, 0.05741933, 0.07479914, 0.08139943, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.0232483 , 0.04694107, 0.04952748, 0.09606499, 0.10513278,
        0.07586014, 0.0624383 , 0.04183603, 0.06365307, 0.07366913,
        0.07851894, 0.05478466, 0.07427127, 0.07350386, 0.07211744,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.0285601 , 0.04683515, 0.05922532, 0.09666843, 0.08798321,
        0.06078727, 0.05569831, 0.04272161, 0.06658986, 0.07611587,
        0.07692442, 0.0570823 , 0.07511929, 0.07561968, 0.07042918,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [56]:
ss_power_over_n

array([0.03289744, 0.02828205, 0.02446154, 0.02197436, 0.02141026,
       0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
       0.05020513, 0.05058974, 0.0474359 , 0.05684615, 0.0505641 ,
       0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
       0.07864103, 0.07041026, 0.05469231, 0.03966667])

In [57]:
power_allocated_cea_using_max_hh_dd = np.minimum(max_hh_dd.values, ss_power_over_n)

In [58]:
power_allocated_cea_using_max_hh_dd

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04739652, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02141026,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04183603, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02141026,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04272161, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [59]:
power_allocated_cea_using_max_hh_dd_columns = ['power_allocated_cea_from_max_hour_1',
                                               'power_allocated_cea_from_max_hour_2',
                                               'power_allocated_cea_from_max_hour_3',
                                               'power_allocated_cea_from_max_hour_4',
                                               'power_allocated_cea_from_max_hour_5',
                                               'power_allocated_cea_from_max_hour_6',
                                               'power_allocated_cea_from_max_hour_7',
                                               'power_allocated_cea_from_max_hour_8',
                                               'power_allocated_cea_from_max_hour_9',
                                               'power_allocated_cea_from_max_hour_10',
                                               'power_allocated_cea_from_max_hour_11',
                                               'power_allocated_cea_from_max_hour_12',
                                               'power_allocated_cea_from_max_hour_13',
                                               'power_allocated_cea_from_max_hour_14',
                                               'power_allocated_cea_from_max_hour_15',
                                               'power_allocated_cea_from_max_hour_16',
                                               'power_allocated_cea_from_max_hour_17',
                                               'power_allocated_cea_from_max_hour_18',
                                               'power_allocated_cea_from_max_hour_19',
                                               'power_allocated_cea_from_max_hour_20',
                                               'power_allocated_cea_from_max_hour_21',
                                               'power_allocated_cea_from_max_hour_22',
                                               'power_allocated_cea_from_max_hour_23',
                                               'power_allocated_cea_from_max_hour_24']

In [60]:
power_allocated_cea_using_max_hh_dd = pd.DataFrame(power_allocated_cea_using_max_hh_dd, columns=power_allocated_cea_using_max_hh_dd_columns)

In [61]:
power_allocated_cea_using_max_hh_dd

power_allocated_cea_from_max_hour_1  power_allocated_cea_from_max_hour_2  \
0                               0.014388                             0.015659   
1                               0.014678                             0.015097   
2                               0.015001                             0.013061   
3                               0.013074                             0.015200   
4                               0.014916                             0.013884   
..                                   ...                                  ...   
151                             0.013944                             0.013327   
152                             0.015180                             0.015824   
153                             0.015635                             0.012813   
154                             0.016478                             0.014699   
155                             0.014277                             0.015265   

     power_allocated_cea_from_max_hour_3  power_allocated_cea_from_max_hour_4  \
0                               0.013455                             0.016010   
1                               0.011827                             0.015693   
2                               0.014182                             0.016672   
3                               0.013378                             0.016499   
4                               0.011294                             0.014167   
..                                   ...                                  ...   
151                             0.011218                             0.017031   
152                             0.013570                             0.015256   
153                             0.013077                             0.014817   
154                             0.014071                             0.014759   
155                             0.014078                             0.014460   

     power_allocated_cea_from_max_hour_5  power_allocated_cea_from_max_hour_6  \
0                               0.019436                             0.021872   
1                               0.021410                             0.021872   
2                               0.021410                             0.021872   
3                               0.021410                             0.021872   
4                               0.018803                             0.021872   
..                                   ...                                  ...   
151                             0.021410                             0.021872   
152                             0.021410                             0.021872   
153                             0.019525                             0.021872   
154                             0.021410                             0.021872   
155                             0.020537                             0.021872   

     power_allocated_cea_from_max_hour_7  power_allocated_cea_from_max_hour_8  \
0                               0.025051                             0.024308   
1                               0.025051                             0.024308   
2                               0.025051                             0.024308   
3                               0.025051                             0.024308   
4                               0.025051                             0.024308   
..                                   ...                                  ...   
151                             0.025051                             0.024308   
152                             0.025051                             0.024308   
153                             0.025051                             0.024308   
154                             0.025051                             0.024308   
155                             0.025051                             0.024308   

     power_allocated_cea_from_max_hour_9  \
0                               0.041462   
1                        

In [62]:
power_allocated_cea_using_max_hh_dd.to_excel('power_allocated_cea_using_max_hh_dd.xlsx', index=False)

## Getting the minimum value between avg_hh_dd and ss_power_over_n 

In [63]:
avg_hh_dd.values

array([[0.01299518, 0.01387844, 0.01243753, 0.01469236, 0.01601493,
        0.02109302, 0.02553345, 0.04920385, 0.07902245, 0.07438506,
        0.04351411, 0.05919352, 0.04448818, 0.04832482, 0.05630871,
        0.06231039, 0.05255316, 0.07085903, 0.06711095, 0.04708656,
        0.03594799, 0.02338703, 0.01675449, 0.01516877],
       [0.01325735, 0.01338088, 0.01093236, 0.01440155, 0.01784319,
        0.02048857, 0.02930005, 0.04165257, 0.06909667, 0.07847968,
        0.05466684, 0.05713154, 0.03926889, 0.0468963 , 0.06365962,
        0.06646566, 0.05014177, 0.07035897, 0.06060133, 0.05443991,
        0.03298148, 0.02660079, 0.0168373 , 0.01574688],
       [0.01354882, 0.0115765 , 0.01310933, 0.01530024, 0.01929728,
        0.02516982, 0.02923394, 0.04980845, 0.0695307 , 0.06567784,
        0.04380493, 0.0509644 , 0.04010013, 0.04905997, 0.06577392,
        0.06511591, 0.05224469, 0.07116232, 0.06234576, 0.05316548,
        0.03143359, 0.02859386, 0.01878637, 0.01453823],
       [0.011

In [65]:
ss_power_over_n

array([0.03289744, 0.02828205, 0.02446154, 0.02197436, 0.02141026,
       0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
       0.05020513, 0.05058974, 0.0474359 , 0.05684615, 0.0505641 ,
       0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
       0.07864103, 0.07041026, 0.05469231, 0.03966667])

In [66]:
power_allocated_cea_using_avg_hh_dd = np.minimum(avg_hh_dd.values, ss_power_over_n)

In [67]:
power_allocated_cea_using_avg_hh_dd

array([[0.01299518, 0.01387844, 0.01243753, 0.01469236, 0.01601493,
        0.02109302, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.04351411, 0.05058974, 0.04448818, 0.04832482, 0.0505641 ,
        0.04866667, 0.05255316, 0.06015385, 0.05138462, 0.04708656,
        0.03594799, 0.02338703, 0.01675449, 0.01516877],
       [0.01325735, 0.01338088, 0.01093236, 0.01440155, 0.01784319,
        0.02048857, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.03926889, 0.0468963 , 0.0505641 ,
        0.04866667, 0.05014177, 0.06015385, 0.05138462, 0.05443991,
        0.03298148, 0.02660079, 0.0168373 , 0.01574688],
       [0.01354882, 0.0115765 , 0.01310933, 0.01530024, 0.01929728,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.04380493, 0.05058974, 0.04010013, 0.04905997, 0.0505641 ,
        0.04866667, 0.05224469, 0.06015385, 0.05138462, 0.05316548,
        0.03143359, 0.02859386, 0.01878637, 0.01453823],
       [0.011

In [68]:
power_allocated_cea_using_avg_hh_dd_columns = ['power_allocated_cea_from_avg_hour_1',
                                               'power_allocated_cea_from_avg_hour_2',
                                               'power_allocated_cea_from_avg_hour_3',
                                               'power_allocated_cea_from_avg_hour_4',
                                               'power_allocated_cea_from_avg_hour_5',
                                               'power_allocated_cea_from_avg_hour_6',
                                               'power_allocated_cea_from_avg_hour_7',
                                               'power_allocated_cea_from_avg_hour_8',
                                               'power_allocated_cea_from_avg_hour_9',
                                               'power_allocated_cea_from_avg_hour_10',
                                               'power_allocated_cea_from_avg_hour_11',
                                               'power_allocated_cea_from_avg_hour_12',
                                               'power_allocated_cea_from_avg_hour_13',
                                               'power_allocated_cea_from_avg_hour_14',
                                               'power_allocated_cea_from_avg_hour_15',
                                               'power_allocated_cea_from_avg_hour_16',
                                               'power_allocated_cea_from_avg_hour_17',
                                               'power_allocated_cea_from_avg_hour_18',
                                               'power_allocated_cea_from_avg_hour_19',
                                               'power_allocated_cea_from_avg_hour_20',
                                               'power_allocated_cea_from_avg_hour_21',
                                               'power_allocated_cea_from_avg_hour_22',
                                               'power_allocated_cea_from_avg_hour_23',
                                               'power_allocated_cea_from_avg_hour_24']

In [69]:
power_allocated_cea_using_avg_hh_dd = pd.DataFrame(power_allocated_cea_using_avg_hh_dd, columns=power_allocated_cea_using_avg_hh_dd_columns)

In [70]:
power_allocated_cea_using_avg_hh_dd

power_allocated_cea_from_avg_hour_1  power_allocated_cea_from_avg_hour_2  \
0                               0.012995                             0.013878   
1                               0.013257                             0.013381   
2                               0.013549                             0.011576   
3                               0.011809                             0.013472   
4                               0.013472                             0.012306   
..                                   ...                                  ...   
151                             0.012594                             0.011812   
152                             0.013710                             0.014025   
153                             0.014121                             0.011356   
154                             0.014883                             0.013028   
155                             0.012895                             0.013529   

     power_allocated_cea_from_avg_hour_3  power_allocated_cea_from_avg_hour_4  \
0                               0.012438                             0.014692   
1                               0.010932                             0.014402   
2                               0.013109                             0.015300   
3                               0.012366                             0.015141   
4                               0.010440                             0.013002   
..                                   ...                                  ...   
151                             0.010370                             0.015629   
152                             0.012543                             0.014001   
153                             0.012088                             0.013598   
154                             0.013006                             0.013545   
155                             0.013013                             0.013270   

     power_allocated_cea_from_avg_hour_5  power_allocated_cea_from_avg_hour_6  \
0                               0.016015                             0.021093   
1                               0.017843                             0.020489   
2                               0.019297                             0.021872   
3                               0.018592                             0.020641   
4                               0.015493                             0.021872   
..                                   ...                                  ...   
151                             0.018682                             0.021872   
152                             0.018828                             0.021174   
153                             0.016088                             0.021872   
154                             0.017923                             0.021872   
155                             0.016922                             0.021872   

     power_allocated_cea_from_avg_hour_7  power_allocated_cea_from_avg_hour_8  \
0                               0.025051                             0.024308   
1                               0.025051                             0.024308   
2                               0.025051                             0.024308   
3                               0.025051                             0.024308   
4                               0.025051                             0.024308   
..                                   ...                                  ...   
151                             0.025051                             0.024308   
152                             0.025051                             0.024308   
153                             0.025051                             0.024308   
154                             0.025051                             0.024308   
155                             0.025051                             0.024308   

     power_allocated_cea_from_avg_hour_9  \
0                               0.041462   
1                        

In [71]:
power_allocated_cea_using_avg_hh_dd.to_excel('power_allocated_cea_using_avg_hh_dd.xlsx', index=False)