In [24]:
import pandas as pd
import numpy as np

from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)

In [25]:
avg_hh_dd = pd.read_excel('avg_hh_demand_reformatted.xlsx')
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
power_allocated_cea_using_avg_hh_dd = pd.read_excel('power_allocated_cea_using_avg_hh_dd.xlsx')
power_allocated_cea_using_max_hh_dd = pd.read_excel('power_allocated_cea_using_max_hh_dd.xlsx')
power_allocated_cea_using_min_hh_dd = pd.read_excel('power_allocated_cea_using_min_hh_dd.xlsx')

## Avg_unmet_demand_cea

In [26]:
avg_hh_dd.values

array([[0.01299518, 0.01387844, 0.01243753, 0.01469236, 0.01601493,
        0.02109302, 0.02553345, 0.04920385, 0.07902245, 0.07438506,
        0.04351411, 0.05919352, 0.04448818, 0.04832482, 0.05630871,
        0.06231039, 0.05255316, 0.07085903, 0.06711095, 0.04708656,
        0.03594799, 0.02338703, 0.01675449, 0.01516877],
       [0.01325735, 0.01338088, 0.01093236, 0.01440155, 0.01784319,
        0.02048857, 0.02930005, 0.04165257, 0.06909667, 0.07847968,
        0.05466684, 0.05713154, 0.03926889, 0.0468963 , 0.06365962,
        0.06646566, 0.05014177, 0.07035897, 0.06060133, 0.05443991,
        0.03298148, 0.02660079, 0.0168373 , 0.01574688],
       [0.01354882, 0.0115765 , 0.01310933, 0.01530024, 0.01929728,
        0.02516982, 0.02923394, 0.04980845, 0.0695307 , 0.06567784,
        0.04380493, 0.0509644 , 0.04010013, 0.04905997, 0.06577392,
        0.06511591, 0.05224469, 0.07116232, 0.06234576, 0.05316548,
        0.03143359, 0.02859386, 0.01878637, 0.01453823],
       [0.011

In [27]:
power_allocated_cea_using_avg_hh_dd.values

array([[0.01299518, 0.01387844, 0.01243753, 0.01469236, 0.01601493,
        0.02109302, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.04351411, 0.05058974, 0.04448818, 0.04832482, 0.0505641 ,
        0.04866667, 0.05255316, 0.06015385, 0.05138462, 0.04708656,
        0.03594799, 0.02338703, 0.01675449, 0.01516877],
       [0.01325735, 0.01338088, 0.01093236, 0.01440155, 0.01784319,
        0.02048857, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.03926889, 0.0468963 , 0.0505641 ,
        0.04866667, 0.05014177, 0.06015385, 0.05138462, 0.05443991,
        0.03298148, 0.02660079, 0.0168373 , 0.01574688],
       [0.01354882, 0.0115765 , 0.01310933, 0.01530024, 0.01929728,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.04380493, 0.05058974, 0.04010013, 0.04905997, 0.0505641 ,
        0.04866667, 0.05224469, 0.06015385, 0.05138462, 0.05316548,
        0.03143359, 0.02859386, 0.01878637, 0.01453823],
       [0.011

In [28]:
avg_unmet_demand_cea = avg_hh_dd.values - power_allocated_cea_using_avg_hh_dd.values

In [29]:
avg_unmet_demand_cea

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.82170229e-04, 2.48961579e-02,
        3.75609086e-02, 3.70004462e-02, 0.00000000e+00, 8.60377349e-03,
        0.00000000e+00, 0.00000000e+00, 5.74460245e-03, 1.36437253e-02,
        0.00000000e+00, 1.07051865e-02, 1.57263345e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.24876968e-03, 1.73448795e-02,
        2.76351331e-02, 4.10950644e-02, 4.46171394e-03, 6.54180101e-03,
        0.00000000e+00, 0.00000000e+00, 1.30955207e-02, 1.77989907e-02,
        0.00000000e+00, 1.02051234e-02, 9.21671707e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.29802281e-03, 4.18265332e-03, 2.5500

In [30]:
column_names = ['avg_unmet_demand_cea_hour_1',
                'avg_unmet_demand_cea_hour_2',
                'avg_unmet_demand_cea_hour_3',
                'avg_unmet_demand_cea_hour_4',
                'avg_unmet_demand_cea_hour_5',
                'avg_unmet_demand_cea_hour_6',
                'avg_unmet_demand_cea_hour_7',
                'avg_unmet_demand_cea_hour_8',
                'avg_unmet_demand_cea_hour_9',
                'avg_unmet_demand_cea_hour_10',
                'avg_unmet_demand_cea_hour_11',
                'avg_unmet_demand_cea_hour_12',
                'avg_unmet_demand_cea_hour_13',
                'avg_unmet_demand_cea_hour_14',
                'avg_unmet_demand_cea_hour_15',
                'avg_unmet_demand_cea_hour_16',
                'avg_unmet_demand_cea_hour_17',
                'avg_unmet_demand_cea_hour_18',
                'avg_unmet_demand_cea_hour_19',
                'avg_unmet_demand_cea_hour_20',
                'avg_unmet_demand_cea_hour_21',
                'avg_unmet_demand_cea_hour_22',
                'avg_unmet_demand_cea_hour_23',
                'avg_unmet_demand_cea_hour_24',]

In [32]:
avg_unmet_demand_cea = pd.DataFrame(avg_unmet_demand_cea, columns=column_names)

In [33]:
avg_unmet_demand_cea

avg_unmet_demand_cea_hour_1  avg_unmet_demand_cea_hour_2  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     avg_unmet_demand_cea_hour_3  avg_unmet_demand_cea_hour_4  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     avg_unmet_demand_cea_hour_5  avg_unmet_demand_cea_hour_6  \
0                            0.0                     0.000000   
1                            0.0                     0.000000   
2                            0.0                     0.003298   
3                            0.0                     0.000000   
4                            0.0                     0.001872   
..                           ...                          ...   
151                          0.0                     0.001822   
152                          0.0                     0.000000   
153                          0.0                     0.000456   
154                          0.0                     0.002104   
155                          0.0                     0.003485   

     avg_unmet_demand_cea_hour_7  avg_unmet_demand_cea_hour_8  \
0                       0.000482                     0.024896   
1                       0.004249                     0.017345   
2                       0.004183                     0.025501   
3                       0.002541                     0.016752   
4                       0.002239                     0.021014   
..                           ...                          ...   
151                     0.005227                     0.017144   
152                     0.000293                     0.017713   
153                     0.005578                     0.019750   
154                     0.002261                     0.024700   
155                     0.000508                     0.016496   

     avg_unmet_demand_cea_hour_9  avg_unmet_demand_cea_hour_10  ...  \
0                       0.037561                      0.037000  ...   
1                       0.027635                      0.041095  ...   
2                       0.028069                      0.028293  ...   
3                       0.042412                      0.035559  ...   
4                       0.043235                      0.029200  ...   
..                           ...                           ...  ...   
151                     0.034917                      0.030933  ...   
152                     0.032734                      0.033642  ...   
153                     0.040332                      0.027095  ...   
154                     0.043968                      0.040006  ...   
155                     0.029445                      0.035081  ...   

     avg_unmet_demand_cea_ho

In [34]:
avg_unmet_demand_cea.to_excel('avg_unmet_demand_cea.xlsx', index=False)

## Min_unmet_demand_cea

In [35]:
min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.04088393, 0.04866755, 0.05500866,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.05163881, 0.04707744, 0.06572936, 0.0547874 , 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.03460951, 0.04255457, 0.05803668,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.05508243, 0.0449173 , 0.06526549, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.0413863 , 0.04282187, 0.04856956,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.05396384, 0.04680111, 0.06601068, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [36]:
power_allocated_cea_using_min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.02430769, 0.04146154, 0.03738462,
        0.03091926, 0.05058974, 0.04124641, 0.03130225, 0.04707986,
        0.04866667, 0.04707744, 0.06015385, 0.05138462, 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.02430769, 0.04146154, 0.03738462,
        0.03884391, 0.05058974, 0.03640745, 0.03037693, 0.0505641 ,
        0.04866667, 0.0449173 , 0.06015385, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.02430769, 0.04146154, 0.03738462,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.0505641 ,
        0.04866667, 0.04680111, 0.06015385, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [37]:
min_unmet_demand_cea = min_hh_dd.values - power_allocated_cea_using_min_hh_dd.values

In [38]:
min_unmet_demand_cea

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.65762420e-02,
        7.20601534e-03, 1.76240417e-02, 0.00000000e+00, 2.01184594e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.97214789e-03,
        0.00000000e+00, 5.57550955e-03, 3.40278350e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.03018149e-02,
        1.09302802e-03, 2.06520616e-02, 0.00000000e+00, 1.79499503e-04,
        0.00000000e+00, 0.00000000e+00, 2.66188439e-03, 6.41576254e-03,
        0.00000000e+00, 5.11164731e-03, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.7078

In [39]:
column_names = ['min_unmet_demand_cea_hour_1',
                'min_unmet_demand_cea_hour_2',
                'min_unmet_demand_cea_hour_3',
                'min_unmet_demand_cea_hour_4',
                'min_unmet_demand_cea_hour_5',
                'min_unmet_demand_cea_hour_6',
                'min_unmet_demand_cea_hour_7',
                'min_unmet_demand_cea_hour_8',
                'min_unmet_demand_cea_hour_9',
                'min_unmet_demand_cea_hour_10',
                'min_unmet_demand_cea_hour_11',
                'min_unmet_demand_cea_hour_12',
                'min_unmet_demand_cea_hour_13',
                'min_unmet_demand_cea_hour_14',
                'min_unmet_demand_cea_hour_15',
                'min_unmet_demand_cea_hour_16',
                'min_unmet_demand_cea_hour_17',
                'min_unmet_demand_cea_hour_18',
                'min_unmet_demand_cea_hour_19',
                'min_unmet_demand_cea_hour_20',
                'min_unmet_demand_cea_hour_21',
                'min_unmet_demand_cea_hour_22',
                'min_unmet_demand_cea_hour_23',
                'min_unmet_demand_cea_hour_24',]

In [40]:
min_unmet_demand_cea = pd.DataFrame(min_unmet_demand_cea, columns=column_names)

In [41]:
min_unmet_demand_cea

min_unmet_demand_cea_hour_1  min_unmet_demand_cea_hour_2  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cea_hour_3  min_unmet_demand_cea_hour_4  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cea_hour_5  min_unmet_demand_cea_hour_6  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cea_hour_7  min_unmet_demand_cea_hour_8  \
0                            0.0                     0.016576   
1                            0.0                     0.010302   
2                            0.0                     0.017079   
3                            0.0                     0.009809   
4                            0.0                     0.013351   
..                           ...                          ...   
151                          0.0                     0.010135   
152                          0.0                     0.010608   
153                          0.0                     0.012300   
154                          0.0                     0.016413   
155                          0.0                     0.009597   

     min_unmet_demand_cea_hour_9  min_unmet_demand_cea_hour_10  ...  \
0                       0.007206                      0.017624  ...   
1                       0.001093                      0.020652  ...   
2                       0.001360                      0.011185  ...   
3                       0.010194                      0.016558  ...   
4                       0.010701                      0.011855  ...   
..                           ...                           ...  ...   
151                     0.005578                      0.013137  ...   
152                     0.004233                      0.015141  ...   
153                     0.008913                      0.010299  ...   
154                     0.011152                      0.019847  ...   
155                     0.002208                      0.016205  ...   

     min_unmet_demand_cea_ho

In [42]:
min_unmet_demand_cea.to_excel('min_unmet_demand_cea.xlsx', index=False)

## Max_unmet_demand_cea

In [43]:
max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02393417, 0.04090667, 0.05850642, 0.10986478, 0.09964756,
        0.06038371, 0.0646918 , 0.04739652, 0.06559203, 0.06516239,
        0.07361013, 0.05741933, 0.07479914, 0.08139943, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.0232483 , 0.04694107, 0.04952748, 0.09606499, 0.10513278,
        0.07586014, 0.0624383 , 0.04183603, 0.06365307, 0.07366913,
        0.07851894, 0.05478466, 0.07427127, 0.07350386, 0.07211744,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.0285601 , 0.04683515, 0.05922532, 0.09666843, 0.08798321,
        0.06078727, 0.05569831, 0.04272161, 0.06658986, 0.07611587,
        0.07692442, 0.0570823 , 0.07511929, 0.07561968, 0.07042918,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [44]:
power_allocated_cea_using_max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04739652, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02141026,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04183603, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02141026,
        0.02187179, 0.02505128, 0.02430769, 0.04146154, 0.03738462,
        0.05020513, 0.05058974, 0.04272161, 0.05684615, 0.0505641 ,
        0.04866667, 0.053     , 0.06015385, 0.05138462, 0.06258974,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [45]:
max_unmet_demand_cea = max_hh_dd.values - power_allocated_cea_using_max_hh_dd.values

In [46]:
max_unmet_demand_cea

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.06237858e-03, 1.58553878e-02, 3.41987246e-02,
        6.84032444e-02, 6.22629433e-02, 1.01785866e-02, 1.41020559e-02,
        0.00000000e+00, 8.74587849e-03, 1.45982901e-02, 2.49434646e-02,
        4.41933373e-03, 1.46452941e-02, 3.00148120e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.44989579e-04, 1.37650883e-03, 2.18897868e-02, 2.52197882e-02,
        5.46034543e-02, 6.77481670e-02, 2.56550156e-02, 1.18485539e-02,
        0.00000000e+00, 6.80691738e-03, 2.31050284e-02, 2.98522707e-02,
        1.78466419e-03, 1.41174250e-02, 2.21192431e-02, 9.52769502e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.00973579e-03, 6.68830597e-03, 2.17838630e-02, 3.4917

In [47]:
column_names = ['max_unmet_demand_cea_hour_1',
                'max_unmet_demand_cea_hour_2',
                'max_unmet_demand_cea_hour_3',
                'max_unmet_demand_cea_hour_4',
                'max_unmet_demand_cea_hour_5',
                'max_unmet_demand_cea_hour_6',
                'max_unmet_demand_cea_hour_7',
                'max_unmet_demand_cea_hour_8',
                'max_unmet_demand_cea_hour_9',
                'max_unmet_demand_cea_hour_10',
                'max_unmet_demand_cea_hour_11',
                'max_unmet_demand_cea_hour_12',
                'max_unmet_demand_cea_hour_13',
                'max_unmet_demand_cea_hour_14',
                'max_unmet_demand_cea_hour_15',
                'max_unmet_demand_cea_hour_16',
                'max_unmet_demand_cea_hour_17',
                'max_unmet_demand_cea_hour_18',
                'max_unmet_demand_cea_hour_19',
                'max_unmet_demand_cea_hour_20',
                'max_unmet_demand_cea_hour_21',
                'max_unmet_demand_cea_hour_22',
                'max_unmet_demand_cea_hour_23',
                'max_unmet_demand_cea_hour_24',]

In [48]:
max_unmet_demand_cea = pd.DataFrame(max_unmet_demand_cea, columns=column_names)

In [49]:
max_unmet_demand_cea

max_unmet_demand_cea_hour_1  max_unmet_demand_cea_hour_2  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     max_unmet_demand_cea_hour_3  max_unmet_demand_cea_hour_4  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     max_unmet_demand_cea_hour_5  max_unmet_demand_cea_hour_6  \
0                       0.000000                     0.002062   
1                       0.000245                     0.001377   
2                       0.002010                     0.006688   
3                       0.001154                     0.001549   
4                       0.000000                     0.005070   
..                           ...                          ...   
151                     0.001263                     0.005013   
152                     0.001441                     0.002155   
153                     0.000000                     0.003463   
154                     0.000342                     0.005334   
155                     0.000000                     0.006900   

     max_unmet_demand_cea_hour_7  max_unmet_demand_cea_hour_8  \
0                       0.015855                     0.034199   
1                       0.021890                     0.025220   
2                       0.021784                     0.034918   
3                       0.019154                     0.024514   
4                       0.018670                     0.029583   
..                           ...                          ...   
151                     0.023457                     0.024981   
152                     0.015552                     0.025658   
153                     0.024019                     0.028080   
154                     0.018705                     0.033966   
155                     0.015896                     0.024211   

     max_unmet_demand_cea_hour_9  max_unmet_demand_cea_hour_10  ...  \
0                       0.068403                      0.062263  ...   
1                       0.054603                      0.067748  ...   
2                       0.055207                      0.050599  ...   
3                       0.075148                      0.060332  ...   
4                       0.076292                      0.051813  ...   
..                           ...                           ...  ...   
151                     0.064727                      0.054135  ...   
152                     0.061692                      0.057764  ...   
153                     0.072256                      0.048993  ...   
154                     0.077311                      0.066290  ...   
155                     0.057120                      0.059692  ...   

     max_unmet_demand_cea_ho

In [50]:
max_unmet_demand_cea.to_excel('max_unmet_demand_cea.xlsx', index=False)