In [1]:
import pandas as pd
import numpy as np

In [3]:
from IPython.display import display

display.max_columns = None  
display.max_rows = None   

np.set_printoptions(threshold=np.inf)

In [4]:
power_allocated_ratio = pd.read_excel('power_allocated_ratio.xlsx')
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')

In [5]:
power_allocated_ratio.values

array([[0.03182767, 0.03161109, 0.02600167, 0.02232175, 0.01953367,
        0.02006426, 0.02228293, 0.02656831, 0.04204389, 0.03897825,
        0.04464012, 0.05594718, 0.05121777, 0.0526553 , 0.04725275,
        0.04499445, 0.05075673, 0.06092182, 0.05081654, 0.05952713,
        0.08118576, 0.06421456, 0.05188414, 0.03843799],
       [0.03246979, 0.0304778 , 0.02285499, 0.02187994, 0.02176362,
        0.01948929, 0.02557002, 0.02249089, 0.03676288, 0.04112386,
        0.05608145, 0.05399829, 0.04520898, 0.05109876, 0.05342145,
        0.04799497, 0.04842777, 0.06049189, 0.04588744, 0.06882328,
        0.07448613, 0.07303868, 0.05214058, 0.03990294],
       [0.03318365, 0.02636793, 0.02740614, 0.0232453 , 0.0235372 ,
        0.02394222, 0.02551232, 0.02689477, 0.03699381, 0.03441561,
        0.04493846, 0.04816937, 0.04616595, 0.05345633, 0.05519571,
        0.04702031, 0.0504588 , 0.06118258, 0.04720832, 0.06721213,
        0.07099035, 0.07851111, 0.05817633, 0.03684019],
       [0.028

In [6]:
min_hh_dd.values

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.04088393, 0.04866755, 0.05500866,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.05163881, 0.04707744, 0.06572936, 0.0547874 , 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.03460951, 0.04255457, 0.05803668,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.05508243, 0.0449173 , 0.06526549, 0.04947314, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.0413863 , 0.04282187, 0.04856956,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.05396384, 0.04680111, 0.06601068, 0.05089723, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [7]:
max_hh_dd.values

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02393417, 0.04090667, 0.05850642, 0.10986478, 0.09964756,
        0.06038371, 0.0646918 , 0.04739652, 0.06559203, 0.06516239,
        0.07361013, 0.05741933, 0.07479914, 0.08139943, 0.06237634,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.0232483 , 0.04694107, 0.04952748, 0.09606499, 0.10513278,
        0.07586014, 0.0624383 , 0.04183603, 0.06365307, 0.07366913,
        0.07851894, 0.05478466, 0.07427127, 0.07350386, 0.07211744,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.0285601 , 0.04683515, 0.05922532, 0.09666843, 0.08798321,
        0.06078727, 0.05569831, 0.04272161, 0.06658986, 0.07611587,
        0.07692442, 0.0570823 , 0.07511929, 0.07561968, 0.07042918,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

## Power allocated demand from min_hh_dd

In [9]:
power_allocated_demand_from_min_hh_dd = np.minimum(min_hh_dd.values, power_allocated_ratio.values)

In [11]:
power_allocated_demand_from_min_hh_dd

array([[0.01076819, 0.01200107, 0.01159449, 0.01380286, 0.01354631,
        0.01794328, 0.0143422 , 0.02656831, 0.04204389, 0.03897825,
        0.03091926, 0.05260159, 0.04124641, 0.03130225, 0.04707986,
        0.04499445, 0.04707744, 0.06092182, 0.05081654, 0.02887369,
        0.03053482, 0.01905833, 0.01615019, 0.01304208],
       [0.01098544, 0.01157082, 0.01019134, 0.01352965, 0.01509275,
        0.01742909, 0.01645791, 0.02249089, 0.03676288, 0.04112386,
        0.03884391, 0.05076924, 0.03640745, 0.03037693, 0.05322599,
        0.04799497, 0.0449173 , 0.06049189, 0.04588744, 0.03338279,
        0.02801502, 0.02167726, 0.01623001, 0.01353914],
       [0.01122696, 0.01001052, 0.01222076, 0.01437394, 0.0163227 ,
        0.02141131, 0.01642077, 0.02689477, 0.03699381, 0.03441561,
        0.0311259 , 0.04528889, 0.03717811, 0.03177844, 0.05499376,
        0.04702031, 0.04680111, 0.06118258, 0.04720832, 0.03260131,
        0.02670022, 0.02330142, 0.01810878, 0.01249994],
       [0.009

In [12]:
columns = ['power_allocated_demand_from_min_hour_1',
           'power_allocated_demand_from_min_hour_2',
           'power_allocated_demand_from_min_hour_3',
           'power_allocated_demand_from_min_hour_4',
           'power_allocated_demand_from_min_hour_5',
           'power_allocated_demand_from_min_hour_6',
           'power_allocated_demand_from_min_hour_7',
           'power_allocated_demand_from_min_hour_8',
           'power_allocated_demand_from_min_hour_9',
           'power_allocated_demand_from_min_hour_10',
           'power_allocated_demand_from_min_hour_11',
           'power_allocated_demand_from_min_hour_12',
           'power_allocated_demand_from_min_hour_13',
           'power_allocated_demand_from_min_hour_14',
           'power_allocated_demand_from_min_hour_15',
           'power_allocated_demand_from_min_hour_16',
           'power_allocated_demand_from_min_hour_17',
           'power_allocated_demand_from_min_hour_18',
           'power_allocated_demand_from_min_hour_19',
           'power_allocated_demand_from_min_hour_20',
           'power_allocated_demand_from_min_hour_21',
           'power_allocated_demand_from_min_hour_22',
           'power_allocated_demand_from_min_hour_23',
           'power_allocated_demand_from_min_hour_24']

In [13]:
power_allocated_demand_from_min_hh_dd = pd.DataFrame(power_allocated_demand_from_min_hh_dd, columns=columns)

In [14]:
power_allocated_demand_from_min_hh_dd

power_allocated_demand_from_min_hour_1  \
0                                  0.010768   
1                                  0.010985   
2                                  0.011227   
3                                  0.009785   
4                                  0.011163   
..                                      ...   
151                                0.010435   
152                                0.011361   
153                                0.011701   
154                                0.012332   
155                                0.010685   

     power_allocated_demand_from_min_hour_2  \
0                                  0.012001   
1                                  0.011571   
2                                  0.010011   
3                                  0.011650   
4                                  0.010641   
..                                      ...   
151                                0.010214   
152                                0.012128   
153                                0.009820   
154                                0.011266   
155                                0.011699   

     power_allocated_demand_from_min_hour_3  \
0                                  0.011594   
1                                  0.010191   
2                                  0.012221   
3                                  0.011528   
4                                  0.009732   
..                                      ...   
151                                0.009667   
152                                0.011693   
153                                0.011268   
154                                0.012125   
155                                0.012131   

     power_allocated_demand_from_min_hour_4  \
0                                  0.013803   
1                                  0.013530   
2                                  0.014374   
3                                  0.014225   
4                                  0.012215   
..                                      ...   
151                                0.014683   
152                                0.013153   
153                                0.012775   
154                                0.012725   
155                                0.012467   

     power_allocated_demand_from_min_hour_5  \
0                                  0.013546   
1                                  0.015093   
2                                  0.016323   
3                                  0.015727   
4                                  0.013105   
..                                      ...   
151                                0.015802   
152                                0.015926   
153                                0.013608   
154                                0.015160   
155                                0.014313   

     power_allocated_demand_from_min_hour_6  \
0                                  0.017943   
1                                  0.017429   
2                                  0.021411   
3                                  0.017559   
4                                  0.020198   
..                                      ...   
151                                0.020156   
152                                0.018012   
153                                0.018994   
154                                0.020396   
155                                0.021570   

     power_allocated_demand_from_min_hour_7  \
0                                  0.014342   
1                                  0.016458   
2                                  0.016421   
3                                  0.015499   
4                                  0.015329   
..                                      ...   
151                                0.017007   
152                                0.014236   
153                                0.017205   
154                                0.015341   
155                                0.014357   

     power_allocated_demand_from_min_hour_8  \
0  

In [15]:
power_allocated_demand_from_min_hh_dd.to_excel('power_allocated_demand_from_min_hh_dd.xlsx', index=False)

## Power allocated demand from max_hh_dd

In [16]:
power_allocated_demand_from_max_hh_dd = np.minimum(max_hh_dd.values, power_allocated_ratio.values)

In [17]:
power_allocated_demand_from_max_hh_dd

array([[0.01438821, 0.01565863, 0.01345521, 0.01600955, 0.0194364 ,
        0.02006426, 0.02228293, 0.02656831, 0.04204389, 0.03897825,
        0.04464012, 0.05594718, 0.04739652, 0.0526553 , 0.04725275,
        0.04499445, 0.05075673, 0.06092182, 0.05081654, 0.05952713,
        0.04029443, 0.0267772 , 0.01727162, 0.01768076],
       [0.01467849, 0.01509725, 0.01182687, 0.01569267, 0.02165525,
        0.01948929, 0.02557002, 0.02249089, 0.03676288, 0.04112386,
        0.05608145, 0.05399829, 0.04183603, 0.05109876, 0.05342145,
        0.04799497, 0.04842777, 0.06049189, 0.04588744, 0.06882328,
        0.03696924, 0.03045682, 0.01735698, 0.01835461],
       [0.0150012 , 0.01306142, 0.01418198, 0.01667193, 0.02341999,
        0.02394222, 0.02551232, 0.02689477, 0.03699381, 0.03441561,
        0.04493846, 0.04816937, 0.04272161, 0.05345633, 0.05519571,
        0.04702031, 0.0504588 , 0.06118258, 0.04720832, 0.06721213,
        0.0352342 , 0.0327388 , 0.01936621, 0.0169458 ],
       [0.013

In [18]:
columns = ['power_allocated_demand_from_max_hour_1',
           'power_allocated_demand_from_max_hour_2',
           'power_allocated_demand_from_max_hour_3',
           'power_allocated_demand_from_max_hour_4',
           'power_allocated_demand_from_max_hour_5',
           'power_allocated_demand_from_max_hour_6',
           'power_allocated_demand_from_max_hour_7',
           'power_allocated_demand_from_max_hour_8',
           'power_allocated_demand_from_max_hour_9',
           'power_allocated_demand_from_max_hour_10',
           'power_allocated_demand_from_max_hour_11',
           'power_allocated_demand_from_max_hour_12',
           'power_allocated_demand_from_max_hour_13',
           'power_allocated_demand_from_max_hour_14',
           'power_allocated_demand_from_max_hour_15',
           'power_allocated_demand_from_max_hour_16',
           'power_allocated_demand_from_max_hour_17',
           'power_allocated_demand_from_max_hour_18',
           'power_allocated_demand_from_max_hour_19',
           'power_allocated_demand_from_max_hour_20',
           'power_allocated_demand_from_max_hour_21',
           'power_allocated_demand_from_max_hour_22',
           'power_allocated_demand_from_max_hour_23',
           'power_allocated_demand_from_max_hour_24']

In [19]:
power_allocated_demand_from_max_hh_dd = pd.DataFrame(power_allocated_demand_from_max_hh_dd, columns=columns)

In [20]:
power_allocated_demand_from_max_hh_dd

power_allocated_demand_from_max_hour_1  \
0                                  0.014388   
1                                  0.014678   
2                                  0.015001   
3                                  0.013074   
4                                  0.014916   
..                                      ...   
151                                0.013944   
152                                0.015180   
153                                0.015635   
154                                0.016478   
155                                0.014277   

     power_allocated_demand_from_max_hour_2  \
0                                  0.015659   
1                                  0.015097   
2                                  0.013061   
3                                  0.015200   
4                                  0.013884   
..                                      ...   
151                                0.013327   
152                                0.015824   
153                                0.012813   
154                                0.014699   
155                                0.015265   

     power_allocated_demand_from_max_hour_3  \
0                                  0.013455   
1                                  0.011827   
2                                  0.014182   
3                                  0.013378   
4                                  0.011294   
..                                      ...   
151                                0.011218   
152                                0.013570   
153                                0.013077   
154                                0.014071   
155                                0.014078   

     power_allocated_demand_from_max_hour_4  \
0                                  0.016010   
1                                  0.015693   
2                                  0.016672   
3                                  0.016499   
4                                  0.014167   
..                                      ...   
151                                0.017031   
152                                0.015256   
153                                0.014817   
154                                0.014759   
155                                0.014460   

     power_allocated_demand_from_max_hour_5  \
0                                  0.019436   
1                                  0.021655   
2                                  0.023420   
3                                  0.022565   
4                                  0.018803   
..                                      ...   
151                                0.022673   
152                                0.022851   
153                                0.019525   
154                                0.021752   
155                                0.020537   

     power_allocated_demand_from_max_hour_6  \
0                                  0.020064   
1                                  0.019489   
2                                  0.023942   
3                                  0.019634   
4                                  0.022586   
..                                      ...   
151                                0.022538   
152                                0.020141   
153                                0.021239   
154                                0.022807   
155                                0.024120   

     power_allocated_demand_from_max_hour_7  \
0                                  0.022283   
1                                  0.025570   
2                                  0.025512   
3                                  0.024080   
4                                  0.023816   
..                                      ...   
151                                0.026424   
152                                0.022118   
153                                0.026730   
154                                0.023835   
155                                0.022305   

     power_allocated_demand_from_max_hour_8  \
0  

In [21]:
power_allocated_demand_from_max_hh_dd.to_excel('power_allocated_demand_from_max_hh_dd.xlsx', index=False)