In [1]:
import numpy as np
import pandas as pd

In [3]:
max_hh_dd = pd.read_excel('max_hh_demand_reformatted.xlsx')
min_hh_dd = pd.read_excel('min_hh_demand_reformatted.xlsx')
min_power_allocated_cel = pd.read_excel('min_allocated_power_cel.xlsx')
max_power_allocated_cel = pd.read_excel('max_allocated_power_cel.xlsx')


In [7]:
min_hh_dd.values 

array([[0.01076819, 0.01200107, 0.01159449, ..., 0.01905833, 0.01615019,
        0.01304208],
       [0.01098544, 0.01157082, 0.01019134, ..., 0.02167726, 0.01623001,
        0.01353914],
       [0.01122696, 0.01001052, 0.01222076, ..., 0.02330142, 0.01810878,
        0.01249994],
       ...,
       [0.01170096, 0.0098201 , 0.01126849, ..., 0.01953368, 0.01636615,
        0.01195468],
       [0.01233218, 0.01126592, 0.01212486, ..., 0.01875512, 0.01676479,
        0.01270151],
       [0.01068518, 0.0116992 , 0.01213087, ..., 0.0224528 , 0.01804679,
        0.01203715]])

In [8]:
min_power_allocated_cel.values

array([[0.01076819, 0.01200107, 0.01159449, ..., 0.01905833, 0.01615019,
        0.01304208],
       [0.01098544, 0.01157082, 0.01019134, ..., 0.02167726, 0.01623001,
        0.01353914],
       [0.01122696, 0.01001052, 0.01222076, ..., 0.02330142, 0.01810878,
        0.01249994],
       ...,
       [0.01170096, 0.0098201 , 0.01126849, ..., 0.01953368, 0.01636615,
        0.01195468],
       [0.01233218, 0.01126592, 0.01212486, ..., 0.01875512, 0.01676479,
        0.01270151],
       [0.01068518, 0.0116992 , 0.01213087, ..., 0.0224528 , 0.01804679,
        0.01203715]])

In [9]:
min_unmet_demand_cel = min_hh_dd.values - min_power_allocated_cel.values

In [10]:
min_unmet_demand_cel

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
columns = ['min_unmet_demand_cel_hour_1',
           'min_unmet_demand_cel_hour_2',
           'min_unmet_demand_cel_hour_3',
           'min_unmet_demand_cel_hour_4',
           'min_unmet_demand_cel_hour_5',
           'min_unmet_demand_cel_hour_6',
           'min_unmet_demand_cel_hour_7',
           'min_unmet_demand_cel_hour_8',
           'min_unmet_demand_cel_hour_9',
           'min_unmet_demand_cel_hour_10',
           'min_unmet_demand_cel_hour_11',
           'min_unmet_demand_cel_hour_12',
           'min_unmet_demand_cel_hour_13',
           'min_unmet_demand_cel_hour_14',
           'min_unmet_demand_cel_hour_15',
           'min_unmet_demand_cel_hour_16',
           'min_unmet_demand_cel_hour_17',
           'min_unmet_demand_cel_hour_18',
           'min_unmet_demand_cel_hour_19',
           'min_unmet_demand_cel_hour_20',
           'min_unmet_demand_cel_hour_21',
           'min_unmet_demand_cel_hour_22',
           'min_unmet_demand_cel_hour_23',
           'min_unmet_demand_cel_hour_24']

In [12]:
min_unmet_demand_cel = pd.DataFrame(min_unmet_demand_cel, columns=columns)

In [13]:
min_unmet_demand_cel

min_unmet_demand_cel_hour_1  min_unmet_demand_cel_hour_2  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cel_hour_3  min_unmet_demand_cel_hour_4  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cel_hour_5  min_unmet_demand_cel_hour_6  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     min_unmet_demand_cel_hour_7  min_unmet_demand_cel_hour_8  \
0                            0.0                     0.014316   
1                            0.0                     0.012119   
2                            0.0                     0.014492   
3                            0.0                     0.011946   
4                            0.0                     0.013186   
..                           ...                          ...   
151                          0.0                     0.012060   
152                          0.0                     0.012226   
153                          0.0                     0.012818   
154                          0.0                     0.014259   
155                          0.0                     0.011872   

     min_unmet_demand_cel_hour_9  min_unmet_demand_cel_hour_10  ...  \
0                       0.006624                      0.016030  ...   
1                       0.005792                      0.016913  ...   
2                       0.005828                      0.014154  ...   
3                       0.007030                      0.015720  ...   
4                       0.007099                      0.014349  ...   
..                           ...                           ...  ...   
151                     0.006402                      0.014723  ...   
152                     0.006219                      0.015307  ...   
153                     0.006856                      0.013896  ...   
154                     0.007161                      0.016678  ...   
155                     0.005943                      0.015617  ...   

     min_unmet_demand_cel_ho

In [14]:
min_unmet_demand_cel.to_excel('min_unmet_demand_cel.xlsx', index=False)

In [15]:
max_unmet_demand_cel = max_hh_dd.values - max_power_allocated_cel.values

In [16]:
columns = ['max_unmet_demand_cel_hour_1',
           'max_unmet_demand_cel_hour_2',
           'max_unmet_demand_cel_hour_3',
           'max_unmet_demand_cel_hour_4',
           'max_unmet_demand_cel_hour_5',
           'max_unmet_demand_cel_hour_6',
           'max_unmet_demand_cel_hour_7',
           'max_unmet_demand_cel_hour_8',
           'max_unmet_demand_cel_hour_9',
           'max_unmet_demand_cel_hour_10',
           'max_unmet_demand_cel_hour_11',
           'max_unmet_demand_cel_hour_12',
           'max_unmet_demand_cel_hour_13',
           'max_unmet_demand_cel_hour_14',
           'max_unmet_demand_cel_hour_15',
           'max_unmet_demand_cel_hour_16',
           'max_unmet_demand_cel_hour_17',
           'max_unmet_demand_cel_hour_18',
           'max_unmet_demand_cel_hour_19',
           'max_unmet_demand_cel_hour_20',
           'max_unmet_demand_cel_hour_21',
           'max_unmet_demand_cel_hour_22',
           'max_unmet_demand_cel_hour_23',
           'max_unmet_demand_cel_hour_24']

In [17]:
max_unmet_demand_cel = pd.DataFrame(max_unmet_demand_cel, columns=columns)

In [18]:
max_unmet_demand_cel

max_unmet_demand_cel_hour_1  max_unmet_demand_cel_hour_2  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     max_unmet_demand_cel_hour_3  max_unmet_demand_cel_hour_4  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
151                          0.0                          0.0   
152                          0.0                          0.0   
153                          0.0                          0.0   
154                          0.0                          0.0   
155                          0.0                          0.0   

     max_unmet_demand_cel_hour_5  max_unmet_demand_cel_hour_6  \
0                            0.0                     0.003870   
1                            0.0                     0.003759   
2                            0.0                     0.004618   
3                            0.0                     0.003787   
4                            0.0                     0.004356   
..                           ...                          ...   
151                          0.0                     0.004347   
152                          0.0                     0.003885   
153                          0.0                     0.004096   
154                          0.0                     0.004399   
155                          0.0                     0.004652   

     max_unmet_demand_cel_hour_7  max_unmet_demand_cel_hour_8  \
0                       0.018624                     0.031938   
1                       0.021371                     0.027037   
2                       0.021323                     0.032331   
3                       0.020126                     0.026651   
4                       0.019905                     0.029418   
..                           ...                          ...   
151                     0.022085                     0.026906   
152                     0.018486                     0.027276   
153                     0.022341                     0.028598   
154                     0.019921                     0.031811   
155                     0.018642                     0.026486   

     max_unmet_demand_cel_hour_9  max_unmet_demand_cel_hour_10  ...  \
0                       0.067821                      0.060669  ...   
1                       0.059302                      0.064009  ...   
2                       0.059675                      0.053568  ...   
3                       0.071984                      0.059494  ...   
4                       0.072691                      0.054307  ...   
..                           ...                           ...  ...   
151                     0.065552                      0.055720  ...   
152                     0.063678                      0.057930  ...   
153                     0.070199                      0.052590  ...   
154                     0.073320                      0.063121  ...   
155                     0.060855                      0.059104  ...   

     max_unmet_demand_cel_ho

In [19]:
max_unmet_demand_cel.to_excel('max_unmet_demand_cel.xlsx', index=False)